.nh
.TH I3KING   2025-03-30 budlabs "User Manuals"
.SH NAME
i3king \- window ruler

.SH SYNOPSIS
\fBi3king [OPTIONS]\fR

.SH OPTIONS
.EX
-a, --apply                | Match all existing windows against the rules and exit.
-c, --config         FILE  | use FILE as config  
-n, --conid          CONID | window with CONID, match against rules and exit exit.
--dryrun                   | Parse rules but don't execute commands.
-h, --help                 | print help and exit  
--json               JSON  | use JSON instead of output from: `i3-msg -t subscribe`
--log                FILE  | print messages to FILE instead of STDERR  
--no-apply                 | dont re-apply the rules on i3 crash 
--no-restart               | dont restart on i3 crash  
--print-commands           | Print commands to STDOUT instead of executing them.
--reload                   | force reload of i3king  
--verbose                  | More verbose output to **STDERR**.  
-v, --version              | print version info and exit  
-d, --winid          WINID | window with WINID, match against rules and exit exit.  
.EE

.SS -c, --config         FILE
Override the value of the Environment variable
\fBI3_KING_RULE_FILE\fP . Or the default value:
.br
\fB~/.config/i3king/rules\fR

.SS --no-apply
If this option is set it will not automatically
apply rules to all windows when the IPC socket is
broken (happens on a crash or on \fBrestart\fR).
This option has no effect if \fB--no-restart\fR is used.

.SS --no-restart
When the IPC socket is broken, i3king will automatically
restart if this option is not set.

.SH USAGE
i3king will match all \fBnew\fP windows against the
rules defined in \fBI3_KING_RULE_FILE\fP
(\fI\fB~/.config/i3king/rules\fR\fP). If a rule matches
the created window, the command associated with
the rule will get passed to \fBi3-msg\fR\&.

.PP
The criterias a window can get matched against are
.br
- \fBclass\fP
- \fBinstance\fP
- \fBtitle\fP
- \fBwindow_type\fP
- \fBwindow_role\fP

.PP
Use \fBGLOBAL\fP rules to match any windows. global
rules can have a \fBblack\fPlist for windows that
will not trigger the rule.

.PP
A variant of the GLOBAL rule is \fBDEFAULT\fP rules,
which works exactly like GLOBAL rules, except they
only get triggered if the window didn't match any
\fI"normal"\fP rules (regular GLOBAL rules are normal).

.PP
\fBON_CLOSE\fP work like normal rules but will only
trigger when a window is closed.

.PP
Just like in the i3 config the \fBset\fR directive is
available, so you can make variables.

.PP
Some built in magic variables are avaible in the config:
.IP \(bu 2
$INSTANCE
.IP \(bu 2
$CLASS
.IP \(bu 2
$CONID
.IP \(bu 2
$WINID
.IP \(bu 2
$TITLE

.PP
\fBTITLE\fP is a rule type that works slightly different
than the others. If triggered it will always execute
the command \fBtitle_format NEW_TITLE\fR\&. And triggers
on new windows and when a window title changes.

.PP
Instead of a command you specify: \fB[option]/REGEX/ template\fR
Use \fB$1,$2,$3...\fR in the template to expand them to
the corresponding capture group from the regex.

.PP
\fB[option]\fR is optional and can be either:
.br
- \fB~0\fR remove expanded $HOME/ from NEW_TITLE
  \fIif this results in empty NEW_TITLE, a single \fB~\fR will be used\fP
- \fB~1\fR replace expanded $HOME with \fB~\fR

.SH EXAMPLE
.EX
# assuming the window class is "Thunar" and the window
# title is something like "/home/anon/.config/i3 - Thunar"

TITLE class=Thunar
  /^(.+)\\s-\\s(Thunar)$/ Filemanager: $2 - $1

# the above will result in NEW_TITLE: 
# Filemanager: Thunar - /home/anon/.config/i3

TITLE class=Thunar
  ~0/^(.+)\\s-\\s(Thunar)$/ $1

# the above will result in NEW_TITLE: 
# .config/i3

TITLE class=Thunar
  ~1/^(.+)\\s-\\s(Thunar)$/ $1

# the above will result in NEW_TITLE: 
# ~/.config/i3

.EE

.SH EXAMPLE
.EX
GLOBAL \\
  class=URxvt instance=htop, \\
  instance=firefox
    title_format $INSTANCE
.EE

.PP
The above rule will set the title_format to the instance
name of all windows, except a URxvt window with the
instance name htop, and firefox windows.

.PP
If $I3_KING_RULES_FILE doesn't exist,
a example rule file will get created. See that
file for details about the syntax.

.PP
If you used to have \fBfor_window\fR rules that triggered
\fBi3fyra --move\fR commands. It is recommended to use
the built in varialbe \fB$CONID\fP when executing i3fyra:

.SH EXAMPLE
.EX
# old i3 version:
for_window [instance=qutebrowser] exec --no-startup-id i3fyra --move C

# with i3 king:
instance=qutebrowser
  exec --no-startup-id i3fyra --conid $CONID --move C
.EE

.PP
(\fIthe \fB--conid\fR option in i3fyra is brand new\fP)

.PP
If the \fBrestart\fR command is issued from i3, all
windows lose gets new container IDs, marks are
lost and other more or less strange things might
happen to the layout. Another thing is that all
open IPC sockets are closed and this means that
any ipc subscriber would have to be restarted.
\fBi3king\fP will, when the socket is broken, match
all known windows against the rules again, and
automatically restart itself. If you for some
reason don't want this behaviour, try \fB--no-
restart\fR and/or \fB--no-apply\fR options.

.SH protip
Sending USR1 to the i3king process will restart
i3king. Hint: \fBkill -USR1 $(< "$XDG_RUNTIME_DIR/i3ass/i3king.pid")\fR

.SH ENVIRONMENT
.SS BASHBUD_DIR
bashbud config dir location.

.SS I3_KING_RULE_FILE
Path to file containing rules to be parsed.

.SS I3_KING_PID_FILE
When i3king is running this file contains the pid
of the i3king process. It is used by \fBi3fyra\fP to
know if i3king is running, if it is, it will try
to match windows against the rules when \fB--float\fR
option toggles the floating state to tiled.

.SH CONTACT
Send bugs and feature requests to:
.br
https://github.com/budlabs/i3ass/issues

.SH COPYRIGHT
Copyright (c) 2021-2025, budRich of budlabs
.br
SPDX-License-Identifier: MIT
