.TH I3VISWIZ 1 2018\-06\-30 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3viswiz\fR \- Professional window focus for i3wm

.SH SYNOPSIS
.PP
\fB\fCi3viswiz\fR [\fB\fC\-v\fR|\fB\fC\-h\fR]
.br
\fB\fCi3viswiz\fR [\fB\fC\-p\fR \fB\fCt\fR|\fB\fCc\fR|\fB\fCi\fR|\fB\fCn\fR|\fB\fCo\fR|\fB\fCd\fR]
.br
\fB\fCi3viswiz\fR [\fB\fC\-g\fR \fIGAPSIZE\fP] [\fIDIRECTION\fP]

.SH DESCRIPTION
.PP
\fB\fCi3viswiz\fR either prints a list of the currently visible
tiled windows to \fB\fCstdout\fR or shifts the focus depending on
the arguments.

.PP
If a \fIDIRECTION\fP (left|right|up|down)
is passed, \fB\fCi3wizvis\fR will shift the focus to the
window closest in the given DIRECTION, or warp
focus if there are no windows in the given direction.

.SH OPTIONS
.PP
\fB\fC\-v\fR
.br
Show version and exit.

.PP
\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-p\fR|\fB\fC\-t\fR|\fB\fC\-c\fR|\fB\fC\-i\fR|\fB\fC\-n\fR|\fB\fC\-o\fR|\fB\fC\-d\fR
.br
Print list of windows to \fB\fCstdout\fR\&. The first line is either
the \fIcon\_id\fP of the window receiving focus . The second line
are the x and y coordinates where receiving window is searched.
Remaining lines are the list. The first field is marked with a
\fB\fC*\fR if the line contains the active window.

.PP
Depending on the option the last field of the output
contains different information about the window.

.PP
\fB\fC\-t\fR title
.br
\fB\fC\-c\fR class
.br
\fB\fC\-i\fR instance
.br
\fB\fC\-o\fR title\_format
.br
\fB\fC\-n\fR con\_id
.br
\fB\fC\-d\fR window\_id
.br
\fB\fC\-p\fR parent container

.PP
Floating windows are excluded from the list.
If the active window is floating, the first line
will have the text "floating".

.PP
\fB\fC\-g\fR GAPSIZE
.br
Set GAPSIZE (defaults to 5). GAPSIZE is the distance in pixels
from the current window where new focus will be searched.

.PP
\fIDIRECTION\fP
.br
Can be either (left|right|up|down) OR (l|r|u|d). DIRECTION needs
to be the last argument of the command. If no DIRECTION is given,
focus will not shift.

.SH EXAMPLE
.PP
replace the normal i3 focus keybindings with viswiz
like this:

.PP
.RS

.nf
  Normal binding:
  bindsym Mod4+Shift+Left   focus left
  
  Wizzy binding:
  bindsym Mod4+Left   exec \-\-no\-startup\-id i3viswiz l 

.fi
.RE

.PP
example output:

.PP
.RS

.nf
  $ i3viswiz \-o \-g 20 down
  target\_con\_id: 94851559487504
  tx: 582 ty: 470 wall: none
  * 94851560291216 x: 0     y: 0     w: 1165  h: 450   | URxvt
  \- 94851559487504 x: 0     y: 451   w: 1165  h: 448   | sublime
  \- 94851560318768 x: 1166  y: 0     w: 433   h: 899   | bin

.fi
.RE

.SH AUTHOR
.PP
budRich 
\[la]robstenklippa@gmail.com\[ra]

\[la]https://budrich.github.io\[ra]

.SH SEE ALSO
.PP
i3(1)
