#!/bin/bash

NAME="i3viswiz"
VERSION="0.018"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2018-01-18"
UPDATED="2018-06-30"

main(){
  
  while getopts :vhg:pcitod option; do
    case "${option}" in
      g) gapsz=${OPTARG} ;;
      c|i|t|o|p|d) printwhat=$option ;;
      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h|*) printinfo && exit ;;
    esac
  done

  (($#==1)) && [[ $1 =~ p|c|t|i|o ]] && shift $((--OPTIND))
  (($#>1)) && shift $((--OPTIND))

  gapsz=${gapsz:-5}
  dir="${1:0:1}"
  dir="${dir,,}"

  [[ ! $dir =~ u|d|l|r ]] && [[ -n $dir ]] \
    && printinfo && exit

  trgwin="$(listvisible)"

  if [[ -n $printwhat ]]; then
    echo -e "$trgwin"
    exit
  fi

  eval "$(echo -e "$trgwin" | head -1)"

  if [[ $trgcon = floating ]] && [[ -n $dir ]]; then

    case $dir in
      l ) dir=left   ;;
      r ) dir=right  ;;
      u ) dir=left   ;;
      d ) dir=right  ;;
    esac

    i3-msg -q focus $dir

  else
    [[ -z $trgcon ]] && [[ -n $dir ]] \
      && ((gapsz+=75)) && eval "$(listvisible | head -1)"

    [[ -n $trgcon ]] && [[ -n $dir ]] \
      && i3-msg -q "[con_id=$trgcon]" focus
  fi
  
}

listvisible(){
  i3-msg -t get_tree \
           | awk -v opret="$printwhat" -v gapsz=$gapsz -v dir=$dir -v RS=',' -F':' '

    function listvis(id,achld,curc,c,schld,curs,s,stackh) {
      stackh=0

      if(ac[id]["layout"]=="stacked"){
        split(ac[id]["childs"],schld," ")
        for (s in schld) {
          curs=schld[s]
          gsub("[^0-9]","",curs)
          if(curs==""){continue}
          stackh++
        }
        stackh--
      }

      if(ac[id]["layout"]~/tabbed|stacked/){
        ac[id]["childs"]=ac[id]["focused"]}

      split(ac[id]["childs"],achld," ")
      for (c in achld) {
        curc=achld[c]
        gsub("[^0-9]","",curc)
        if(curc==""){continue}
        if(ac[id]["layout"]=="stacked"){
          ac[curc]["h"]=ac[curc]["h"]+(ac[curc]["b"]*stackh)
          ac[curc]["y"]=ac[curc]["y"]-(ac[curc]["b"]*stackh)
        }
        if (ac[curc]["childs"]!="")
          listvis(curc)
        else if (ac[curc]["f"]!=1)
          avis[curc]=curc
      }
    }

    BEGIN{focs=0;end=0;csid="first";actfloat=""}

    ac[cid]["counter"]=="go" && $1=="\"nodes\"" && $2!="[]"{
      ac[cid]["counter"]=csid
      csid=cid
    }

    $1~"{\"id\"" || $2~"\"id\"" {cid=$NF}

    $1=="\"layout\""{clo=$2}

    $1=="\"type\"" && $2=="\"workspace\"" {wsdchk="1"}
    wsdchk=="1" && $1=="\"width\""  {dim["w"]=$2}
    wsdchk=="1" && $1=="\"height\"" {gsub("}","",$2);dim["h"]=$2;wsdchk="2"}

    wsdchk=="1" && $(NF-1) ~ /"x"/ {dim["x"]=$NF}
    wsdchk=="1" && $(NF-1) ~ /"y"/ {dim["y"]=$NF}

    wsdchk=="2" && $1=="\"num\"" {
      dim[$2]["w"]=dim["w"]
      dim[$2]["h"]=dim["h"]
      dim[$2]["x"]=dim["x"]
      dim[$2]["y"]=dim["y"]
      wsdchk="0"
    }

    $1=="\"num\"" {cws=$2;cwsid=cid}

    $1=="\"focused\"" && $2=="true" {
      act=cid
      aws=cws
      awsid=cwsid
    }

    $1=="\"window\"" && $2=="null" {
      gsub("[\"]","",clo)
      ac[cid]["layout"]=clo
      ac[cid]["counter"]="go"
      ac[cid]["focused"]="X"
    }


    $1~"title_format" {ac[cid]["tf"]=$2}
    $1~"title" {ac[cid]["ttl"]=$2}
    $1=="\"window\"" {ac[cid]["wid"]=$2}
    # $1~"id" {ac[cid][]=$2}
    $1~"instance" {ac[cid]["ins"]=$2;ac[cid]["par"]=curpar}
    $1~"class" || $2~"class" {ac[cid]["cls"]=$NF}

    $1=="\"marks\"" {
      gsub("[[]|[]]|\"","",$2);
      if ($2 ~ /^i34.$/){
        sub("i34","",$2)
        curpar=$2
      }
    }


    $1=="\"window\"" && $2!="null" {
      ac[cid]["x"]=curx
      ac[cid]["y"]=cury
      ac[cid]["w"]=curw
      ac[cid]["h"]=curh
      ac[cid]["b"]=curb
    }

    $1=="\"rect\"" {curx=$3;rectw=1}
    rectw==1 && $1=="\"y\""{cury=$2}
    rectw==1 && $1=="\"width\""{curw=$2-1}
    rectw==1 && $1=="\"height\""{sub("}","",$2);curh=$2-1;rectw=2}

    $1=="\"deco_rect\"" {rectb=1}
    rectb==1 && $1=="\"height\""{
      sub("}","",$2)
      curh+=$2;cury-=$2
      curb=$2
      rectb=2
    }

    $1=="\"floating\"" && $2~"_on" {
      if(cid==act){actfloat="floating"}
      ac[cid]["f"]=1
    }

    $1=="\"focus\"" && $2!="[]" {focs=1}
    focs=="1" && $NF~"[]]$"{end=1}
    focs=="1" {
      gsub("[]]|[[]","",$NF)
      if(ac[csid]["focused"]=="X"){ac[csid]["focused"]=$NF}

      ac[csid]["childs"]=$NF" "ac[csid]["childs"]
    }

    end=="1" {
      csid=ac[csid]["counter"]
      focs=0;end=0
    }

    END{
      # cleantree(awsid)
      # # getconts(awsid)
      # # painttree(awsid)

      listvis(awsid)
      wall="none"

      wsh=int(dim[aws]["h"])
      wsw=int(dim[aws]["w"])
      wsx=int(dim[aws]["x"])
      wsy=int(dim[aws]["y"])

      if (dir=="r"){
        trgx=ac[act]["x"]+ac[act]["w"]+gapsz
        trgy=(gapsz+ac[act]["y"])+ac[act]["h"]/2

        if(trgx>(wsw+wsx)){
          trgx=gapsz
          wall="right"
        }
      }

      if (dir=="l"){
        trgx=ac[act]["x"]-gapsz
        trgy=(gapsz+ac[act]["y"])+ac[act]["h"]/2
        if(trgx<wsx){
          trgx=dim[aws]["w"]-gapsz
          wall="left"
        }
      }

      if (dir=="u"){
        trgx=(gapsz+ac[act]["x"])+ac[act]["w"]/2
        trgy=ac[act]["y"]-gapsz
        if(trgy<wsy){
          trgy=dim[aws]["h"]-gapsz
          wall="up"
        }
      }

      if (dir=="d"){
        trgx=(gapsz+ac[act]["x"])+ac[act]["w"]/2
        trgy=ac[act]["y"]+ac[act]["h"]+gapsz
        
        if(trgy>(wsh+wsy)){
          trgy=gapsz
          wall="down"
        }
      }

      trgx=int(trgx)
      trgy=int(trgy)

      if(actfloat==""){
        for (w in avis) {
          hit=0
          hity=0
          hitx=0
          xar=ac[w]["x"]+ac[w]["w"]
          if(trgx>=ac[w]["x"])
            if(xar>=trgx){++hitx;++hit}
          if(trgy>=ac[w]["y"] && trgy<=(ac[w]["y"]+ac[w]["h"]))
            {hity++;hit++}

          if (hit==2){
            tpar=ac[w]["par"]
            tcon=w
            break
          }

          
        }
      } 
      else
        tpar="floating"

      print \
        "trgcon=" tcon, "trgx=" trgx, "trgy=" trgy, \
        "wall=" wall, "trgpar=" tpar, \
        "sx=" dim[aws]["x"], \
        "sy=" dim[aws]["y"], \
        "sw=" dim[aws]["w"], \
        "sh=" dim[aws]["h"] 
      for (w in avis) {
        if(w==act)
          printf "* "
        else
          printf "- "

        printf w " "
        if (opret=="t"){tmpop="| " ac[w]["ttl"]}
        else if (opret=="c"){tmpop="| " ac[w]["cls"]}
        else if (opret=="p"){tmpop="| " ac[w]["par"]}
        else if (opret=="i"){tmpop="| " ac[w]["ins"]}
        else if (opret=="o"){tmpop="| " ac[w]["tf"]}
        else if (opret=="d"){tmpop="| " ac[w]["wid"]}
        else {tmpop=""}

        split("xywh",s,"")
        for (c in s)
          printf sprintf("%2s %-6s", s[c]":", ac[w][s[c]])
        gsub("[\"]","",tmpop)
        print tmpop 
      }
    }
  '
}


printinfo(){
about='
`i3viswiz` - Professional window focus for i3wm

SYNOPSIS
--------

`i3viswiz` [`-v`|`-h`]  
`i3viswiz` [`-p` `t`|`c`|`i`|`n`|`o`|`d`]   
`i3viswiz` [`-g` *GAPSIZE*] [*DIRECTION*]  

DESCRIPTION
-----------

`i3viswiz` either prints a list of the currently visible
tiled windows to `stdout` or shifts the focus depending on
the arguments.  

If a *DIRECTION* (left|right|up|down) 
is passed, `i3wizvis` will shift the focus to the
window closest in the given DIRECTION, or warp
focus if there are no windows in the given direction.  

OPTIONS
-------

`-v`  
Show version and exit.

`-h`  
Show help and exit.

`-p`|`-t`|`-c`|`-i`|`-n`|`-o`|`-d`  
Print list of windows to `stdout`. The first line is either
the *con_id* of the window receiving focus . The second line 
are the x and y coordinates where receiving window is searched.
Remaining lines are the list. The first field is marked with a 
`*` if the line contains the active window.  

Depending on the option the last field of the output
contains different information about the window.

`-t` title  
`-c` class  
`-i` instance  
`-o` title_format  
`-n` con_id  
`-d` window_id  
`-p` parent container  

Floating windows are excluded from the list.
If the active window is floating, the first line
will have the text "floating".  

`-g` GAPSIZE  
Set GAPSIZE (defaults to 5). GAPSIZE is the distance in pixels
from the current window where new focus will be searched.  

*DIRECTION*  
Can be either (left|right|up|down) OR (l|r|u|d). DIRECTION needs
to be the last argument of the command. If no DIRECTION is given,
focus will not shift.  

EXAMPLE
-------

replace the normal i3 focus keybindings with viswiz 
like this:  
``` text
  Normal binding:
  bindsym Mod4+Shift+Left   focus left
  
  Wizzy binding:
  bindsym Mod4+Left   exec --no-startup-id i3viswiz l 
```  

example output:  
``` text
  $ i3viswiz -o -g 20 down
  target_con_id: 94851559487504
  tx: 582 ty: 470 wall: none
  * 94851560291216 x: 0     y: 0     w: 1165  h: 450   | URxvt
  - 94851559487504 x: 0     y: 451   w: 1165  h: 448   | sublime
  - 94851560318768 x: 1166  y: 0     w: 433   h: 899   | bin
```
'

bouthead="
${NAME^^} 1 ${UPDATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

i3(1)
"

  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
