.TH I3FLIP 1 2019\-02\-19 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3flip\fR \- Tabswitching done right

.SH SYNOPSIS
.PP
.RS

.nf
i3flip DIRECTION
i3flip \-\-move|\-m DIRECTION
i3flip \-\-help|\-h
i3flip \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
\fB\fCi3flip\fR switch containers without leaving the
parent. Perfect for tabbed or stacked layout, but
works on all layouts. If direction is \fB\fCnext\fR and
the active container is the last, the first
container will be activated.

.PP
\fBDIRECTION\fP can be either \fIprev\fP or \fInext\fP,
which can be defined with different words:

.PP
\fBnext\fP|right|down|n|r|d
.br
\fBprev\fP|left|up|p|l|u

.SH OPTIONS
.PP
\fB\fC\-\-move\fR|\fB\fC\-m\fR DIRECTION
.br
Move the current tab instead of changing focus.

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH EXAMPLES
.PP
\fB\fC\~/.config/i3/config\fR:

.PP
.RS

.nf
\&...
bindsym Mod4+Tab         exec \-\&\-\&no\-\&startup\-\&id i3flip next
bindsym Mod4+Shift+Tab   exec \-\&\-\&no\-\&startup\-\&id i3flip prev

.fi
.RE

.SH DEPENDENCIES
.PP
\fB\fCi3\fR \fB\fCgawk\fR

.PP
budRich 
\[la]https://github.com/budlabs/i3ass\[ra]

.SH SEE ALSO
.PP
i3(1),
