.nh
.TH I3FLIP 1 2020\-08\-09 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3flip\fR \- Tabswitching done right

.SH SYNOPSIS
.PP
.RS

.nf
i3flip [\-\-move|\-m] [\-\-json JSON] [\-\-verbose] [\-\-dryrun] DIRECTION
i3flip \-\-help|\-h
i3flip \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
\fB\fCi3flip\fR switch containers without leaving the
parent. Perfect for tabbed or stacked layout, but
works on all layouts. If direction is \fB\fCnext\fR and
the active container is the last, the first
container will get focused.

.PP
\fBDIRECTION\fP can be either \fIprev\fP or \fInext\fP,
which can be defined with different words:

.PP
\fBnext\fP|right|down|n|r|d
.br
\fBprev\fP|left|up|p|l|u

.SH OPTIONS
.PP
\fB\fC\-\-move\fR|\fB\fC\-m\fR
.br
Move the current container instead of changing
focus.

.PP
\fB\fC\-\-json\fR JSON
.br
use JSON instead of output from  \fB\fCi3\-msg \-t
get\_tree\fR

.PP
\fB\fC\-\-verbose\fR
.br
Print more information to \fBstderr\fP\&.

.PP
\fB\fC\-\-dryrun\fR
.br
Don't execute any \fIi3 commands\fP\&.

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH EXAMPLES
.PP
\fB\fC\~/.config/i3/config\fR:

.PP
.RS

.nf
\&...
bindsym Mod4+Tab         exec \-\&\-\&no\-\&startup\-\&id i3flip next
bindsym Mod4+Shift+Tab   exec \-\&\-\&no\-\&startup\-\&id i3flip prev

.fi
.RE

.SH DEPENDENCIES
.PP
\fB\fCi3\fR \fB\fCi3viswiz\fR

.PP
budRich https://github.com/budlabs/i3ass
\[la]https://github.com/budlabs/i3ass\[ra]

.SH SEE ALSO
.PP
i3(1),
