.nh
.TH I3KORNHE 1 2021\-05\-28 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3Kornhe\fR \- move and resize windows gracefully

.SH SYNOPSIS
.PP
.RS

.nf
i3Kornhe DIRECTION [\-\-verbose] [\-\-array ARRAY] [\-\-json JSON]
i3Kornhe move [\-\-speed|\-p SPEED] [DIRECTION]
i3Kornhe size [\-\-speed|\-p SPEED] [DIRECTION]
i3Kornhe 1\-9 [\-\-margin INT] [\-\-margin\-top INT] [\-\-margin\-bottom INT] [\-\-margin\-left INT] [\-\-margin\-right INT]
i3Kornhe x
i3Kornhe \-\-help|\-h
i3Kornhe \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
i3Kornhe provides an alternative way to move and
resize windows in \fBi3\fP\&. It has some more
functions then the defaults and is more
streamlined. Resizing floating windows is done by
first selecting a corner of the window, and then
moving that corner. See the wiki or the manpage
for details and how to add the required mode in
the i3 config file that is needed to use
\fBi3Kornhe\fP\&.

.SH OPTIONS
.PP
\fB\fC\-\-verbose\fR

.PP
\fB\fC\-\-array\fR ARRAY

.PP
\fB\fC\-\-json\fR JSON

.PP
\fB\fC\-\-speed\fR|\fB\fC\-p\fR SPEED
.br
Sets speed or distance in pixels to use when
moving and resizing the windows.

.PP
\fB\fC\-\-margin\fR INT

.PP
\fB\fC\-\-margin\-top\fR INT
.br
Override the top\-margin value. Defaults to the
value of \fB\fC\-\-margin\fR (which is 5)

.PP
\fB\fC\-\-margin\-bottom\fR INT
.br
Override the bottom\-margin value. Defaults to the
value of \fB\fC\-\-margin\fR (which is 5)

.PP
\fB\fC\-\-margin\-left\fR INT
.br
Override the left\-margin value. Defaults to the
value of \fB\fC\-\-margin\fR (which is 5)

.PP
\fB\fC\-\-margin\-right\fR INT
.br
Override the right\-margin value. Defaults to the
value of \fB\fC\-\-margin\fR (which is 5)

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCi3\fR \fB\fCi3list\fR \fB\fCi3var\fR

.PP
budRich https://github.com/budlabs/i3ass
\[la]https://github.com/budlabs/i3ass\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), i3(1), i3list(1), i3var(1),
