.nh
.TH I3VAR 1 2021\-05\-28 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3var\fR \- Set or get a i3 variable

.SH SYNOPSIS
.PP
.RS

.nf
i3var set VARNAME [VALUE] [\-\-json JSON]
i3var get VARNAME [\-\-json JSON]
i3var \-\-help|\-h
i3var \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
\fB\fCi3var\fR is used to get or set a "variable" that
is bound to the current i3wm session.  The
variable is actually the mark on the \fBroot
container\fP\&.

.PP
\fB\fCset\fR  [VALUE]
.br
If \fIVARNAME\fP doesn't exist, a new window and mark
will be created.  If \fIVARNAME\fP exists, it's value
will be replaced with \fIVALUE\fP\&.
.br
If \fIVALUE\fP is not defined,  \fIVARNAME\fP will get
unset (the mark is removed).

.PP
\fB\fCget\fR
.br
if \fIVARNAME\fP exists,  its value will be printed
to \fBSTDOUT\fP\&.

.SH OPTIONS
.PP
\fB\fC\-\-json\fR JSON
.br
Use JSON instead of the output of \fB\fCi3\-msg \-t
get\_tree\fR

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCi3\fR

.PP
budRich https://github.com/budlabs/i3ass
\[la]https://github.com/budlabs/i3ass\[ra]

.SH SEE ALSO
.PP
bash(1), i3(1),
