#!/usr/bin/env bash

projectdir="$1"

if [[ -d "$projectdir/conf" ]]; then
  libf="$projectdir/lib/createconf.sh"
  {
    echo -e '#!/usr/bin/env bash' 
    echo
    echo 'createconf() {'
    echo 'local trgdir="$1"'
    echo 'declare -a aconfdirs'
    echo
    echo 'aconfdirs=('
    find "$projectdir/conf" -type d ! -path "$projectdir/conf" | \
      sed -e "s;$projectdir/conf;\"\$trgdir;" \
      -e 's/$/"/'
    echo ')'
    echo
    echo 'mkdir -p "${aconfdirs[@]}"'
    echo
    OFS="${IFS}"
    IFS=$'\n'
    while read -r conffile; do
      echo "cat << 'EOCONF' > \"${conffile/$projectdir\/conf/\$trgdir}\""
      cat "$conffile"
      echo "EOCONF"
      echo
    done <<< "$(find "$projectdir/conf" -type f)"
    IFS="${OFS}"
    echo '}'
    
  } > "$libf"
fi
