#!/usr/bin/env bash

projectdir="$1"
newver="$(date +%Y.%m.%d).0"
curver="$(bashbud --get version "$projectdir")"

[[ ${newver%.*} = "${curver%.*}" ]] && {
  controldigit="${curver##*.}"
  newver="${newver%.*}.$((controldigit+1))"
}

bashbud --set version "$newver" "$projectdir"
