#!/bin/bash

: "${I3RUN_BOTTOM_GAP:=10}"
: "${I3RUN_TOP_GAP:=10}"
: "${I3RUN_LEFT_GAP:=10}"
: "${I3RUN_RIGHT_GAP:=10}"

main(){

  declare -ag _criteria  # options passed to i3list/i3get/i3viswiz
  declare -A  i3list     # globals array
  declare -g  _msgstring # passed to i3-msg ( messy() )

  for k in instance class title conid winid; do
    [[ ${_o[$k]} ]] || continue
    _criteria+=("--$k" "${_o[$k]}")
  done ; unset -v k

  [[ -z ${_criteria[*]} ]] \
    && ERX "please specify a criteria"

  ((_o[verbose])) && ERM "i3run -> i3list ${_criteria[*]}"
  _array=$(i3list "${_criteria[@]}")
  eval "$_array"

  _command=${_o[command]:-$*}

  # if window doesn't exist, launch the command.
  if [[ ${i3list[TWC]} ]]
    then focuswindow
    else [[ ${_o[hide]} ]] || launchcommand
  fi

  ((_o[verbose])) || qflag=-q
  [[ $_msgstring ]] && >&2 i3-msg ${qflag:-} "$_msgstring"
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
