#!/bin/bash

: "${I3RUN_BOTTOM_GAP:=10}"
: "${I3RUN_TOP_GAP:=10}"
: "${I3RUN_LEFT_GAP:=10}"
: "${I3RUN_RIGHT_GAP:=10}"

main(){

  declare -ag _criteria   # options passed to i3list/i3get/i3viswiz
  declare -A   i3list     # globals array
  declare -g  _msgstring  # passed to i3-msg ( messy() )
  declare -ag _pass_array # helper var for storing --array option
  declare -ag _command    # command to execute
  declare -g  _array      # result of i3list

  for k in instance class title conid winid; do
    [[ ${_o[$k]} ]] || continue
    _criteria+=("--$k" "${_o[$k]}")
  done ; unset -v k

  [[ -z ${_criteria[*]} ]] \
    && ERX "please specify a criteria"

  _array=$(i3list "${_criteria[@]}")
  _pass_array=(${_o[verbose]:+--verbose} --array "$_array")
  eval "$_array"

  # shellcheck disable=SC2206
  # SC2206:  Quote to prevent word splitting/globbin.
  # the only way to win, regarding i3run --command COMMAND
  # is to not use it and do: i3run -- COMMAND , instead 
  if [[ ${_o[command]} ]] 
    then _command=(${_o[command]})
    else _command=("$@")
  fi

  # if window doesn't exist, launch the command.
  if [[ ${i3list[TWC]} ]]
    then focuswindow
    else [[ ${_o[hide]} ]] || launchcommand
  fi
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
