#!/bin/bash

main(){

  [[ ${mark:=$1} ]] || ERX "no name specified"

  w="$(i3-msg open)"
  w="${w//[^0-9]/}"

  messy "[con_id=$w]" floating disable, mark "$mark"
}

__dir=$(dirname $(readlink -f "${BASH_SOURCE[0]}")) #bashbud
source "$__dir/_init.sh"                            #bashbud
