.TH I3ASS 1 2019\-01\-05 Linx "User Manuals"
.SH NAME
.PP
\fB\fCi3ass\fR \- i3 assistance scripts

.SH EXAMPLES
.PP
\fB\fCi3get \-h\fR display [i3get] help

.PP
\fB\fCi3get \-v\fR display [i3get] version

.TS
allbox;
l l 
l l .
\fB\fC\fBfile\fP\fR	\fB\fC\fBfunction\fP\fR
[i3fyra]	An advanced simple layout
[i3run]	Run, Raise or hide a window
[i3get]	Get information about i3
[i3list]	T{
Get lots of information about i3
T}
[i3gw]	Ghost window wrapper script
[i3flip]	Tabswitching done right
[i3viswiz]	T{
Focus switching and visible\-window\-info
T}
[i3var]	Set or get a i3 variable
[i3Kornhe]	T{
move and resize windows gracefully
T}
.TE

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCi3\fR \fB\fCgit\fR

.PP
budRich 
\[la]https://github.com/budlabs/i3ass\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), i3(1), git(1),
