.TH I3ASS 1 2019\-01\-10 Linx "User Manuals"
.SH NAME
.PP
\fB\fCi3ass\fR \- i3 assistance scripts

.SH EXAMPLES
.PP
Execute a script with the \fB\fC\-\-help\fR flag to
display help about the command.

.PP
\fB\fCi3get \-\-help\fR display [i3get] help
.br
\fB\fCi3get \-\-version\fR display [i3get] version
.br
\fB\fCman i3get\fR show [i3get] man page
.br
\fB\fCi3ass\fR show version info for all scripts and
dependencies.

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCi3\fR \fB\fCgit\fR

.PP
budRich 
\[la]https://github.com/budlabs/i3ass\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), i3(1), git(1),
