#!/bin/bash

NAME="i3gw"
VERSION="0.1"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-01-11"
UPDATED="2017-11-19"

about="
$NAME - $VERSION - $UPDATED
created: $CREATED by $AUTHOR
===============================
A Ghost window wrapper for i3wm.

i3-msg has an undocumented function (open) that creates
empty containers, or as I call them: ghosts.
Since these empty containers doesn't contain any windows
there is no instance/class/title to identify them, making
it difficult to control them. They do however have a con_id and
I found the easiest way to keep track of the ghosts is to
mark them. That is what this script does, it creates a ghost
get its con_id and mark it.

usage
-----
$NAME [-h|-v] MARK

example:
i3gw casper

this will create a ghost marked casper, you can perform any action
you can perform on a regular container.

example:
i3-msg [con_mark=casper] move to workspace 2
i3-msg [con_mark=casper] split v
i3-msg [con_mark=casper] layout tabbed
i3-msg [con_mark=casper] kill

the last example (kill), destroys the container.

If -h is passed as an option this help will be shown.
If -v is passed as an option version info is displayed.

contact
-------
$CONTACT
"

while getopts :vh option
do
  case "${option}" in
    v) printf "$NAME - version: $VERSION\n"  && \
       printf "updated: $UPDATED by $AUTHOR\n" \
        && exit;;
    h) printf "${about}\n" && exit;;
  esac
done

name=${1:?"usage: i3gw MARK, you didn't request a mark."}

w=$(i3-msg open)
i3-msg [con_id=${w:22:-2}] floating disable, mark $name


