.TH I3VISWIZ 1 2019\-02\-19 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3viswiz\fR \- Professional window focus for i3wm

.SH SYNOPSIS
.PP
.RS

.nf
i3viswiz [\-\-gap|\-g GAPSIZE] **DIRECTION**
i3viswiz [\-\-focus|\-f] \-\-title|\-t       [TARGET]
i3viswiz [\-\-focus|\-f] \-\-instance|\-i    [TARGET]
i3viswiz [\-\-focus|\-f] \-\-class|\-c       [TARGET]
i3viswiz [\-\-focus|\-f] \-\-titleformat|\-o [TARGET]
i3viswiz [\-\-focus|\-f] \-\-winid|\-d       [TARGET]
i3viswiz [\-\-focus|\-f] \-\-parent|\-p      [TARGET]
i3viswiz \-\-help|\-h
i3viswiz \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
\fB\fCi3viswiz\fR either prints a list of the currently
visible tiled windows to \fB\fCstdout\fR or shifts the
focus depending on the arguments.

.PP
If a \fIDIRECTION\fP (left|right|up|down) is passed,
\fB\fCi3wizvis\fR will shift the focus to the window
closest in the given \fIDIRECTION\fP, or warp focus if
there are no windows in the given direction.

.SH OPTIONS
.PP
\fB\fC\-\-gap\fR|\fB\fC\-g\fR GAPSIZE
.br
Set GAPSIZE (defaults to 5). GAPSIZE is the
distance in pixels from the current window where
new focus will be searched.

.PP
\fB\fC\-\-focus\fR|\fB\fC\-f\fR
.br
When used in conjunction with: \fB\fC\-\-titleformat\fR,
\fB\fC\-\-title\fR, \fB\fC\-\-class\fR, \fB\fC\-\-instance\fR, \fB\fC\-\-winid\fR or
\fB\fC\-\-parent\fR\&. The \fBCON\_ID\fP of \fBTARGET\fP window
will get focused if it is visible.

.PP
\fB\fC\-\-title\fR|\fB\fC\-t\fR [TARGET]
.br
If \fBTARGET\fP matches the \fBTITLE\fP of a visible
window, that windows  \fBCON\_ID\fP will get printed
to \fB\fCstdout\fR\&. If no \fBTARGET\fP is specified, a list
of all tiled windows will get printed with
\fBTITLE\fP as the last field of each row.

.PP
\fB\fC\-\-instance\fR|\fB\fC\-i\fR [TARGET]
.br
If \fBTARGET\fP matches the \fBINSTANCE\fP of a
visible window, that windows  \fBCON\_ID\fP will get
printed to \fB\fCstdout\fR\&. If no \fBTARGET\fP is
specified, a list of all tiled windows will get
printed with  \fBINSTANCE\fP as the last field of
each row.

.PP
\fB\fC\-\-class\fR|\fB\fC\-c\fR [TARGET]
.br
If \fBTARGET\fP matches the \fBCLASS\fP of a visible
window, that windows  \fBCON\_ID\fP will get printed
to \fB\fCstdout\fR\&. If no \fBTARGET\fP is specified, a list
of all tiled windows will get printed with
\fBCLASS\fP as the last field of each row.

.PP
\fB\fC\-\-titleformat\fR|\fB\fC\-o\fR [TARGET]
.br
If \fBTARGET\fP matches the \fBTITLE\_FORMAT\fP of a
visible window, that windows  \fBCON\_ID\fP will get
printed to \fB\fCstdout\fR\&. If no \fBTARGET\fP is
specified, a list of all tiled windows will get
printed with  \fBTITLE\_FORMAT\fP as the last field
of each row.

.PP
\fB\fC\-\-winid\fR|\fB\fC\-d\fR [TARGET]
.br
If \fBTARGET\fP matches the \fBWIN\_ID\fP of a visible
window, that windows  \fBCON\_ID\fP will get printed
to \fB\fCstdout\fR\&. If no \fBTARGET\fP is specified, a list
of all tiled windows will get printed with
\fBWIN\_ID\fP as the last field of each row.

.PP
\fB\fC\-\-parent\fR|\fB\fC\-p\fR [TARGET]
.br
If \fBTARGET\fP matches the \fBPARENT\fP of a visible
window, that windows  \fBCON\_ID\fP will get printed
to \fB\fCstdout\fR\&. If no \fBTARGET\fP is specified, a list
of all tiled windows will get printed with
\fBPARENT\fP as the last field of each row.

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH EXAMPLES
.PP
replace the normal i3 focus keybindings with
viswiz like this:

.PP
.RS

.nf
Normal binding:
bindsym Mod4+Shift+Left   focus left

Wizzy binding:
bindsym Mod4+Left   exec \-\-no\-startup\-id i3viswiz l 

.fi
.RE

.PP
example output:

.PP
.RS

.nf
$ i3viswiz \-o \-g 20 down
target\_con\_id: 94851559487504
tx: 582 ty: 470 wall: none
* 94851560291216 x: 0     y: 0     w: 1165  h: 450   | URxvt
\- 94851559487504 x: 0     y: 451   w: 1165  h: 448   | sublime
\- 94851560318768 x: 1166  y: 0     w: 433   h: 899   | bin

.fi
.RE

.SH DEPENDENCIES
.PP
\fB\fCbash\fR \fB\fCgawk\fR \fB\fCi3\fR

.PP
budRich 
\[la]https://github.com/budlabs/i3ass\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), i3(1),
