#!/bin/bash

NAME="i3gw"
VERSION="0.142"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-01-11"
UPDATED="2018-06-30"

main(){
  while getopts vh option
  do
    case "${option}" in
      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h) printinfo && exit ;;
      *) printinfo && ERX "not a valid command $0 $*" ;;
    esac
  done

  # w=$(i3-msg open | sed 's/[^0-9]//g')
  w="$(i3-msg open)"
  w="${w//[^0-9]/}"

  i3-msg -q "[con_id=$w]" floating disable, mark "$1"
}

ERX(){ >&2 echo $@ && exit 1 ;}

printinfo(){
about=\
'`i3gw` - A ghost window wrapper for i3wm.

SYNOPSIS
--------

`i3gw` [`-v`|`-h`]  
`i3gw` *MARK*  

DESCRIPTION
-----------

`i3-msg` has an undocumented function: *open*, 
it creates empty containers, or as I call them: ghosts.
Since these empty containers doesn'"'"'t contain any windows
there is no instance/class/title to identify them, making
it difficult to manage them. They do however have a `con_id` and
I found that the easiest way to keep track of ghosts is to
mark them. That is what this script does, it creates a ghost,
get its `con_id` and marks it.


OPTIONS
-------

`-v`
Show version and exit.

`-h`
Show help and exit.


EXAMPLES
--------

`$ i3gw casper`  

this will create a ghost marked casper, you can perform any action
you can perform on a regular container.

``` text
$ i3-msg [con_mark=casper] move to workspace 2
$ i3-msg [con_mark=casper] split v
$ i3-msg [con_mark=casper] layout tabbed
$ i3-msg [con_mark=casper] kill
```

the last command (`kill`), destroys the container.

DEPENDENCIES
------------

i3wm
'

bouthead="
${NAME^^} 1 ${UPDATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

i3(1)
"
  case "$1" in
    m ) printf '# %s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi


