function descriptions() {
  
  desc["CAL"]="Container A Layout"
  desc["CAF"]="Container A Focused container id"
  desc["CAW"]="Container A Workspace number"
  desc["CAN"]="Container A Workspace name"
  desc["CBL"]="Container B Layout"
  desc["CBF"]="Container B Focused container id"
  desc["CBW"]="Container B Workspace number"
  desc["CBN"]="Container B Workspace name"
  desc["CCL"]="Container C Layout"
  desc["CCF"]="Container C Focused container id"
  desc["CCW"]="Container C Workspace number"
  desc["CCN"]="Container C Workspace name"
  desc["CDL"]="Container D Layout"
  desc["CDF"]="Container D Focused container id"
  desc["CDW"]="Container D Workspace number"
  desc["CDN"]="Container D Workspace name"

  desc["SAB"]="Current split: AB"
  desc["SAC"]="Current split: AC"
  desc["SBD"]="Current split: BD"
  desc["SCD"]="Current split: CD"
  desc["MAB"]="Stored split: AB"
  desc["MAC"]="Stored split: AC"
  desc["MBD"]="Stored split: BD"
  desc["MCD"]="Stored split: CD"
  desc["FAC"]="Family AC memory"
  desc["FBD"]="Family BD memory"
  desc["FCD"]="Family CD memory"
  desc["FAB"]="Family AB memory"

  desc["LVI"]="Visible i3fyra containers"
  desc["LHI"]="Hidden i3fyra containers"
  desc["LAL"]="All containers in family order"
  desc["LEX"]="Existing containers (LVI+LHI)"

  desc["AWF"]="Active Window floating"
  desc["AWP"]="Active Window parent"
  desc["AWC"]="Active Window con_id"
  desc["AWI"]="Active Window id"
  desc["AFT"]="Active Window twin" 
  desc["AFC"]="Active Window cousin" 
  desc["AFS"]="Active Window sibling" 
  desc["AFF"]="Active Window family" 
  desc["AFO"]="Active Window relatives"
  desc["AWW"]="Active Window width"
  desc["AWH"]="Active Window height"
  desc["AWX"]="Active Window x position"
  desc["AWY"]="Active Window y position"
  desc["AWB"]="Active Window titlebar height"
  desc["ATX"]="Active Window tab x postion"
  desc["ATW"]="Active Window tab width"
  desc["ABW"]="Active Window border width"
  desc["APA"]="Active Window parent ID"

  desc["TWF"]="Target Window Floating"
  desc["TWC"]="Target Window con_id"
  desc["TWI"]="Target Window id"
  desc["TWP"]="Target Window Parent container"
  desc["TFT"]="Target Window twin" 
  desc["TFC"]="Target Window cousin" 
  desc["TFS"]="Target Window sibling" 
  desc["TFF"]="Target Window family" 
  desc["TFO"]="Target Window relatives"
  desc["TTX"]="Target Window tab x postion"
  desc["TTW"]="Target Window tab width"
  desc["TWW"]="Target Window width"
  desc["TWH"]="Target Window height"
  desc["TWX"]="Target Window x position"
  desc["TWY"]="Target Window y position"
  desc["TWB"]="Target Window titlebar height"
  desc["TBW"]="Target Window border width"
  desc["TPA"]="Target Window parent ID"
  
  desc["WAW"]="Active Workspace width"
  desc["WAH"]="Active Workspace height"
  desc["WAX"]="Active Workspace x position"
  desc["WAY"]="Active Workspace y position"
  desc["WAN"]="Active Workspace name"
  desc["WSA"]="Active Workspace number"
  desc["WAI"]="Active Workspace con_id"
  desc["WST"]="Target Workspace Number"
  desc["WTN"]="Target Workspace name"
  desc["WTH"]="Target Workspace Height"
  desc["WTI"]="Target Workspace con_id"
  desc["WTW"]="Target Workspace Width"
  desc["WTX"]="Target Workspace X poistion"
  desc["WTY"]="Target Workspace Y position"
  desc["WSF"]="i3fyra Workspace Number"
  desc["WFH"]="i3fyra Workspace Height"
  desc["WFI"]="i3fyra Workspace con_id"
  desc["WFW"]="i3fyra Workspace Width"
  desc["WFX"]="i3fyra Workspace X position"
  desc["WFY"]="i3fyra Workspace Y position"
  desc["WFN"]="i3fyra Workspace name"

  desc["XAB"]="family AB workspace number"
  desc["XAC"]="family AC workspace number"
  desc["XCD"]="family CD workspace number"
  desc["XBD"]="family BD workspace number"

  desc["NAB"]="family AB workspace name"
  desc["NAC"]="family AC workspace name"
  desc["NCD"]="family CD workspace name"
  desc["NBD"]="family BD workspace name"

  desc["VPA"]="virtual position A"
  desc["VPB"]="virtual position B"
  desc["VPC"]="virtual position C"
  desc["VPD"]="virtual position D"

  desc["RID"]="root container id"
  desc["RED"]="last applied layout"

  desc["ORI"]="i3fyra orientation"
  desc["SUS"]="containers matching all criteria"
}
