#!/bin/bash

: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${I3MENU_DIR:=$XDG_CONFIG_HOME/i3menu}"

main(){

  _menu_command="
    rofi -theme <(themefile)
    ${_o[options]:+${_o[options]}}
    ${_o[filter]:+-filter \"${_o[filter]}\"}
    ${_o[show]:+-show \"${_o[show]}\"}
    ${_o[modi]:+-modi \"${_o[modi]}\"}
    ${_o[prompt]:+-p \"${_o[prompt]} \"}
  "

  _menu_command=${_menu_command//$'\n'/ }

  [[ -n ${_o[modi]}${_o[show]} ]] || {

    _menu_command+="-dmenu "

    # if we have stuff on stdin, put
    # that in a tempfile that way we can do stuff ( wc in setincludes() )
    # without worrying that we close and lose whats in stdin
    _tmp_list_file=$(mktemp)
    trap 'rm -f "$_tmp_list_file"' EXIT INT

    if [[ -d ${_o[list-directory]} ]]; then
      l=("${_o[list-directory]%/}/"*)
      printf "%s\n" "${l[@]##*/}" > "$_tmp_list_file"
    elif [[ ! -t 0 ]]; then
      cp /dev/stdin "$_tmp_list_file"
      # if STDIN was empty, delete tmp file
      [[ $(< "$_tmp_list_file") ]] || rm "$_tmp_list_file"
    else
      rm "$_tmp_list_file"
    fi
  }

  # default includes
  : "${_o[include]:=pel}"

  declare -A i3list
  eval "$(eval i3list "${_o[target]}")"

  [[ ${_o[layout]} =~ ^[ABCD]$ ]] \
    && _o[layout]=$(getvirtualpos "${_o[layout]}")

  setgeometry "${_o[layout]:-default}"
  setincludes

  # SC2016  Expressions don't expand in single quotes
  # shellcheck disable=SC2016

  # this ugly hack prints the selected item with
  # list-directory prefixed. But it is important
  # to check that we have selected something, before
  # adding the prefix, therefor tee.
  [[ -d ${_o[list-directory]} ]] && _menu_command+='
    | tee /tmp/i3menu-jank \
    | [[ $(cat) ]] && { 
        echo -n "${_o[list-directory]%/}/" 
        cat /tmp/i3menu-jank
      } ; rm /tmp/i3menu-jank'

  if [[ -f $_tmp_list_file && ${_o[top]} ]]; then
    awk -f <(topsort) "$_tmp_list_file"
  elif [[ -f $_tmp_list_file ]]; then
    cat "$_tmp_list_file"
  fi | {
    ((_o[verbose])) && verbose_outro
    ((_o[dryrun]))  || eval "$_menu_command"
  }
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
