.TH I3GW 1 2019\-02\-19 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3gw\fR \- a ghost window wrapper for i3wm

.SH SYNOPSIS
.PP
.RS

.nf
i3gw MARK
i3gw \-\-help|\-h
i3gw \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
\fB\fCi3\-msg\fR has an undocumented function: \fIopen\fP,
it creates empty containers,  or as I call them:
ghosts.  Since these empty containers doesn't
contain any windows  there is no
instance/class/title to identify them,  making it
difficult to manage them.  They do however have a
\fB\fCcon\_id\fR  and I found that the easiest way to keep
track of ghosts, is to mark them.  That is what
this script does,  it creates a ghost,  get its
\fB\fCcon\_id\fR and marks it.

.SH OPTIONS
.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH EXAMPLES
.PP
\fB\fC$ i3gw casper\fR

.PP
this will create a ghost marked casper,  you can
perform any action you can perform on a regular
container.

.PP
.RS

.nf
$ i3\-msg [con\_mark=casper] move to workspace 2
$ i3\-msg [con\_mark=casper] split v
$ i3\-msg [con\_mark=casper] layout tabbed
$ i3\-msg [con\_mark=casper] kill

.fi
.RE

.PP
the last command (\fB\fCkill\fR), destroys the
container.

.SH DEPENDENCIES
.PP
\fB\fCi3\fR

.PP
budRich 
\[la]https://github.com/budlabs/i3ass\[ra]

.SH SEE ALSO
.PP
i3(1),
