#!/usr/bin/env bash

projectdir="$1"

[[ -d $projectdir/awklib ]] && {
  # update ass list
  {
    echo '#!/usr/bin/env bash'
    echo
    echo 'awklib() {'
    echo "cat << 'EOB'"
    cat "$projectdir/awklib/"*
    echo 'EOB'
    echo '}'
  } > "$projectdir/lib/awklib.sh"  
}
