.TH I3FLIP 1 2018\-09\-01 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3flip\fR \- Tabswitching done right

.SH SYNOPSIS
.PP
\fB\fCi3flip\fR \fB\fC\-v\fR|\fB\fC\-h\fR
.br
\fB\fCi3flip\fR n|r|d|next|right|down
.br
\fB\fCi3flip\fR p|l|u|prev|left|up

.SH DESCRIPTION
.PP
\fB\fCi3flip\fR switch containers without leaving the
parent. Perfect for tabbed or stacked layout, but
works on all layouts. If direction is \fB\fCnext\fR (or
\fB\fCn\fR) and the active container is the last, the
first container will be activated.

.SH OPTIONS
.PP
\fB\fC\-v\fR|\fB\fC\-\-version\fR
.br
Show version and exit.

.PP
\fB\fC\-h\fR|\fB\fC\-\-help\fR
.br
Show help and exit.

.SH EXAMPLE
.PP
Put these keybinding definitions in the i3 config.

.PP
\fB\fC\~/.config/i3/config\fR:

.PP
.RS

.nf
bindsym Mod4+Tab         exec \-\-no\-startup\-id i3flip next
bindsym Mod4+Shift+Tab   exec \-\-no\-startup\-id i3flip prev

.fi
.RE

.PP
Mod4/Super/Windows+Tab will switch to the next tab.

.SH AUTHOR
.PP
budRich 
\[la]robstenklippa@gmail.com\[ra]

\[la]https://budrich.github.io\[ra]

.SH SEE ALSO
.PP
i3(1)
