.nh
.TH I3FLIP   2024-04-21 budlabs "User Manuals"
.SH NAME
i3flip \- Tabswitching done right

.SH SYNOPSIS
\fBi3flip [--move|-m] DIRECTION\fR

.SH OPTIONS
.EX
--dryrun           | don't execute any commands  
-h, --help         | print help and exit  
--json        JSON | use JSON instead of output of `i3-msg -t get_tree`  
-m, --move         | move instead of focus shift  
--verbose          | louder output  
-v, --version      | print version info and exit  
.EE

.PP
\fBi3flip\fR switch containers without leaving the
parent. Perfect for tabbed or stacked layout, but
works on all layouts. If direction is \fBnext\fR and
the active container is the last, the first
container will get focused.

.PP
\fBDIRECTION\fP can be either \fIprev\fP or \fInext\fP, which
can be defined with different words:

.PP
\fBnext\fP|right|down|n|r|d
.br
\fBprev\fP|left|up|p|l|u

.SS examples
\fB~/.config/i3/config\fR:

.EX
\&...
bindsym Mod4+Tab         exec --no-startup-id i3flip next
bindsym Mod4+Shift+Tab   exec --no-startup-id i3flip prev
.EE

.SH CONTACT
Send bugs and feature requests to:
.br
https://github.com/budlabs/i3ass/issues

.SH COPYRIGHT
Copyright (c) 2018-2025, budRich of budlabs
.br
SPDX-License-Identifier: MIT
