.nh
.TH I3ASS   2023-08-19 budlabs "User Manuals"
.SH NAME
.PP
i3ass - Print environment information

.SH SYNOPSIS
.PP
\fB\fCi3ass\fR

.SH OPTIONS
.PP
.RS

.nf
-h, --help     | print help and exit  
-v, --version  | print messages to stderr  

.fi
.RE

.SH USAGE
.PP
The \fB\fCi3ass\fR command is used to print information
about the current environment relevant to i3ass.
The version, update date and installation path of
the other commands in i3ass. Version of the commands
\fB\fCi3, xdotool, gawk, bash\fR\&. And the environment variables:
.br
I3FYRA_WS and I3FYRA_MAIN_CONTAINER.

.SH CONTACT
.PP
Send bugs and feature requests to:
.br
https://github.com/budlabs/i3ass/issues

.SH COPYRIGHT
.PP
Copyright (c) 2023, budRich of budlabs
.br
SPDX-License-Identifier: MIT
