#!/bin/bash

main(){

  for ass in i3{flip,fyra,get,gw,king,Kornhe,list,var,viswiz,zen}; do
    path=$(command -v "$ass")
    version_output=$("$ass" -v 2>&1)
    
    # i3ass - version: 0.0.1
    # updated: 2023-07-12 by budRich
    [[ $path ]] \
      && read -rs _ _ _ version _ updated _ \
         <<< "${version_output//$'\n'/ }" 

    printf "%-8s | %-7s | %-10s | %s\n" \
      "$ass" "${version:--}" "${updated:--}" "${path/~/'~'}"
  done

  echo
  echo -------------------------------------------
  echo

  for cmd in i3 bash gawk xdotool ; do
    if command -v "$cmd" >/dev/null ; then
      "$cmd" --version 2>&- | head -n1
    else
      echo "WARNING: command $cmd not found"
    fi
  done

  echo
  echo -------------------------------------------
  echo
  export | grep I3FYRA | cut -f3 -d' '
}

__dir=$(dirname $(readlink -f "${BASH_SOURCE[0]}")) #bashbud
source "$__dir/_init.sh"                            #bashbud
