#!/bin/bash

main(){

  for ass in i3{flip,fyra,get,gw,king,Kornhe,list,run,var,viswiz,zen,menu,term}; do
    path=$(command -v "$ass")
    
    
    # i3ass - version: 0.0.1
    # updated: 2023-07-12 by budRich
    if [[ $path ]]; then
      version_output=$("$ass" -v 2>&1)
      read -rs _ _ _ version _ updated _ \
         <<< "${version_output//$'\n'/ }" 

      printf "%-8s | %-7s | %-10s | %s\n" \
        "$ass" "${version:--}" "${updated:--}" "${path/~/'~'}"
    else
      printf "%-8s | MISSING! %s\n" "$ass"
    fi

    [[ $ass = i3zen ]] && echo
  done

  echo
  echo -------------------------------------------
  echo

  for cmd in i3 bash gawk xdotool ; do
    if command -v "$cmd" >/dev/null
      then "$cmd" --version 2>&- | head -n1
      else echo "WARNING: command $cmd not found"
    fi
  done

  if command -v dmenu >/dev/null
    then dmenu -v 2>&-
    else "WARNING: command $cmd not found"
  fi

  echo
  echo -------------------------------------------
  echo
  export | grep I3FYRA | cut -f3 -d' '
}

__dir=$(dirname $(readlink -f "${BASH_SOURCE[0]}")) #bashbud
source "$__dir/_init.sh"                            #bashbud
