#!/bin/bash

NAME="termrun"
VERSION="0.021"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-11-15"
UPDATED="2017-11-19"

about="
$NAME - $VERSION - $UPDATED
created: $CREATED by $AUTHOR
===============================
Uses i3run to run or raise a window with the instancename COMMAND.
If no window is found, COMMAND is ran in an urxvt instance with the same 
instance name as COMMAND. When the command exits window is cleared 
and returned to bash. 

I just made this script to keep my i3config cleaner, and to be able to set
fixedsys as the font. Probably needs tweaking if someone other then budRich
uses it ;)

usage
-----
$NAME COMMAND

example:
bindsym Mod3+o exec --no-startup-id exec termrun htop

dependencies
------------

* urxvt

contact
-------
$CONTACT
"

while getopts :vh option
do
  case "${option}" in
    v) printf "$NAME - version: $VERSION\n"  && \
       printf "updated: $UPDATED by $AUTHOR\n" \
        && exit;;
    h) printf "${about}\n" && exit;;
  esac
done

termcmd=$(cat << EOF
urxvtc -name $1 -e bash -c \
  "printf '\e]710;%s\007' 'xft:Fixedsys Excelsior 3.01\-L2 Mono:style=Regular' \
  && $1 && clear && bash"
EOF
)

i3run -i $1 -e "$termcmd"
