#!/bin/bash

NAME="termrun"
VERSION="0.021"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-11-15"
UPDATED="2017-11-19"

about="
$NAME - $VERSION - $UPDATED
created: $CREATED by $AUTHOR
*******************************

Launch a command in a new urxvt window
======================================
Uses [i3run](/i3ass/i3run) to run or raise a window with the instancename: 
\`COMMAND\`. If no window is found, \`COMMAND\` is ran in a urxvt window 
with the same instance name as \`COMMAND\`. When the command exits 
window is cleared and returned to bash.

dependencies
------------
- urxvt
- [i3run](/i3ass/i3run)

usage
-----
\`i3term COMMAND\`

| option | argument | function                  
|:-------|:---------|:--------------------------
| -v     |          | show version info and exit
| -h     |          | show this help and exit   


**example:**  
\`bindsym Mod3+o exec --no-startup-id exec termrun htop\`

contact
-------
$CONTACT
"

while getopts :vh option
do
  case "${option}" in
    v) printf '%s\n' \
         "$NAME - version: $VERSION" \
         "updated: $UPDATED by $AUTHOR"
       exit ;;
    h) printf '%s\n' "${about}" && exit ;;
  esac
done

termcmd=$(cat << EOF
urxvtc -name $1 -e bash -c \
'echo -ne "\e]0;'$1'\007" && $1 && clear && bash'
EOF
)

i3run -i "$1" -e "${termcmd}"
