#!/bin/bash

main(){

  : "${_o[verbose]:=$I3_ASS_VERBOSE}"

  ((_o[verbose])) && timer start i3list

  for o in instance class conid winid mark title titleformat type role parent; do

    [[ ${_o[$o]} ]] || continue

    case "$o" in
      role        ) json_key=window_role     ;;
      type        ) json_key=window_type     ;;
      titleformat ) json_key=title_format    ;;
      parent      ) json_key=i3fyracontainer ;;
      title       ) json_key=name            ;;
      winid       ) json_key=window          ;;
      conid       ) json_key=id              ;;
      mark        ) json_key=marks           ;;
      *           ) json_key=$o              ;;
    esac

    begin_block+="arg_search[\"$json_key\"]=\"${_o[$o]}\";"

  done

  awk -f <(
    echo "BEGIN { $begin_block }"
    _awklib
  ) FS=: RS=, <<< "${_o[json]:-$(i3-msg -t get_tree)}}"

  ((_o[verbose])) && timer stop i3list
  
}

__dir=$(dirname $(readlink -f "${BASH_SOURCE[0]}")) #bashbud
source "$__dir/_init.sh"                            #bashbud
main "$@"                                           #bashbud
