.TH FOCUSVISIBLE 1 2018\-06\-06 Linux "User Manuals"
.SH NAME
.PP
\fB\fCfocusvisible\fR \- Focus a visible window matching a criterion

.SH SYNOPSIS
.PP
\fB\fCSCRIPTNAME\fR \fB\fC\-v\fR|\fB\fC\-\-version\fR
.br
\fB\fCSCRIPTNAME\fR \fB\fC\-h\fR|\fB\fC\-\-help\fR
.br
\fB\fCSCRIPTNAME\fR \fB\fC\-c\fR|\fB\fC\-\-class\fR CLASS
.br
\fB\fCSCRIPTNAME\fR \fB\fC\-i\fR|\fB\fC\-\-instance\fR INSTANCE

.SH OPTIONS
.PP
\fB\fC\-v\fR|\fB\fC\-\-version\fR
.br
Show version and exit.

.PP
\fB\fC\-h\fR|\fB\fC\-\-help\fR
.br
Show help and exit.

.PP
\fB\fC\-c\fR|\fB\fC\-\-class\fR CLASS
Focus a visible window with a matching CLASS.

.PP
\fB\fC\-i\fR|\fB\fC\-\-instance\fR INSTANCE
Focus a visible window with a matching INSTANCE.

.SH DEPENDENCIES
.PP
getvisible

.SH AUTHOR
.PP
budRich 
\[la]robstenklippa@gmail.com\[ra]

\[la]https://budrich.github.io\[ra]

.SH SEE ALSO
.PP
i3viswiz(1), getvisible
