.TH I3POCUS 1 2018\-01\-10 Linux "User Manuals"
.SH NAME
.PP
\fB\fCi3pocus\fR \- Intelligent window focusing

.SH SYNOPSIS
.PP
\fB\fCi3pocus\fR [\fB\fC\-v\fR|\fB\fC\-h\fR] [\fB\fCDIRECTION\fR]

.SH DESCRIPTION
.PP
\fB\fCi3pocus\fR is meant as a replacement for the default
focusing function (\fB\fCi3\-msg focus\fR) in \fBi3wm\fP\&.
\fB\fCi3pocus\fR moves the focus differently depending on
the layout the current window is places in AND the
the layout of the \fIreceiving\fP container AND the
DIRECTION the focus is moved.

.PP
If the focus is moved horizontally (left|right) into
a horizontally split (splith) container, either the
first (DIRECTION = right) or the last (DIRECTION = left)
window will be focused. This differ from the default
built in focus function, which always focus the window
that was last focused inside the container.

.PP
A similar logic is applied to vertical focus/splits.

.PP
If the receiving container layout is tabbed or stacked,
the focused (visible) container will get focus.

.PP
If the current window is in a tabbed or stacked layout,
the parent container will be focused before moving the
focus in DIRECTION.

.SH OPTIONS
.PP
\fB\fC\-v\fR
.br
  Show version and exit.

.PP
\fB\fC\-h\fR
.br
  Show help and exit.

.PP
\fB\fCDIRECTION\fR
.br
  Direction to move the focus, can be either:
.br
  left, right, up, down OR l,r,u,d

.SH EXAMPLES
.PP
You can replace the default focus keybindings in
\fB\fC\~/.config/i3/config\fR with i3pocus in this fashion:

.PP
.RS

.nf
# Default keybinding:
bindsym $mod+Left focus left

# With i3pocus:
# this assumes `i3pocus` is an executable file in your $PATH
bindsym $mod+Left i3pocus left

.fi
.RE

.SH DEPENDENCIES
.PP
i3

.SH AUTHOR
.PP
budRich 
\[la]robstenklippa@gmail.com\[ra]

\[la]https://budrich.github.io\[ra]

.SH SEE ALSO
.PP
i3(1)
