.nh
.TH I3FYRA   2025-12-27 budlabs "User Manuals"
.SH NAME
i3fyra \- An advanced, simple grid-based tiling layout

.SH SYNOPSIS
.EX
i3fyra --show|-s CONTAINER
i3fyra --float|-a
i3fyra --hide|-z CONTAINER
i3fyra --layout|-l LAYOUT [--array ARRAY]
i3fyra --move|-m DEST [--conid|-n CON_ID] [--speed|-p INT]
i3fyra --orientation ORIENTATION
i3fyra --clear-virtuals
i3fyra --mono|-M
i3fyra --swap|-S sibling|family|cycle|cycleCC|cycleCW
i3fyra [--verbose] [--dryrun] [--force|-f] 
i3fyra --help|-h
i3fyra --version|-v 
.EE

.PP
The layout consists of four containers:

.EX
  A B
  C D
.EE

.PP
A container can contain one or more windows. The
internal layout of the containers doesn't matter.
By default the layout of each container is
tabbed.

.PP
A is always to the left of B and D. And always
above C. B is always to the right of A and C. And
always above D.

.PP
This means that the containers will change names
if their position changes.

.PP
The size of the containers are defined by the
three splits: AB, AC and BD.

.PP
Container A and C belong to one family.
.br
Container B and D belong to one family.

.PP
The visibility of containers and families can be
toggled. Not visible containers are placed on the
scratchpad.

.PP
The visibility is toggled by either using \fB--show\fR
or \fB--hide\fR\&. But more often by moving a container
in an \fIimpossible\fP direction,(\fIsee examples
below\fP).

.PP
The \fBi3fyra\fP layout is only active on one
workspace. That workspace can be set with the
environment variable: \fBi3FYRA_WS\fR, otherwise the
workspace active when the layout is created will
be used.

.PP
The benefit of using this layout is that the
placement of windows is more predictable and
easier to control. Especially when using tabbed
containers, which are very clunky to use
with \fIdefault i3\fP\&.


.SH examples
If containers \fBA\fP,\fBB\fP and \fBC\fP are visible
but \fBD\fP is hidden or none existent, the visible
layout would looks like this:

.EX
  A B
  C B
.EE

.PP
If action: \fB--move up\fR would be executed when
container \fBB\fP is active and \fBD\fP is hidden.
Container \fBD\fP would be shown. If action would
have been: \fB--move down\fR, \fBD\fP would be shown
but \fBB\fP would be placed below \fBD\fP, this means
that the containers will also swap names. If
action would have been \fB--move left\fR the active
window in B would be moved to container \fBA\fP\&. If
action was \fB--move right\fR, \fBA\fP and \fBC\fP would
be hidden:

.EX
  B B
  B B
.EE

.PP
If we now \fB--move left\fR, \fBA\fP and \fBC\fP
would be shown again but to the right of \fBB\fP,
the containers would also change names, so \fBB\fP
becomes \fBA\fP, \fBA\fP becomes \fBB\fP and \fBC\fP
becomes \fBD\fP:

.EX
  A B
  A D
.EE

.PP
If this doesn't make sense, check out this
demonstration on youtube:
https://youtu.be/kU8gb6WLFk8

.SH OPTIONS
.EX
--array              ARRAY                                | ARRAY should be the output of `i3list`  
--clear-virtuals                                          | clear/reset virtual positions  
-n, --conid          CON_ID                               | window with **CON_ID** will be used instead of active window  
--dryrun                                                  | don't execute wm commands  
-a, --float                                               | toggle floating state of a window  
-f, --force                                               | ignore virtual positioning.  
-h, --help                                                | print help and exit  
-z, --hide           CONTAINER                            | Hide target containers if visible.  
-l, --layout         LAYOUT                               | update the size of the layout  
-M, --mono                                                | toggle monocle mode 
-m, --move           DEST                                 | move window/create container  
--orientation        ORIENTATION                          | main split orientation on i3fyra WS (horizontal|vertical|toggle)
-s, --show           CONTAINER                            | Show target container.  
-p, --speed          INT                                  | distance in px a floating windows will be moved  
-S, --swap           sibling|family|cycle|cycleCC|cycleCW | switch position with <sibling|family>  
--verbose                                                 | print more stuff to stderr  
-v, --version                                             | louder output  
.EE

.SS --array              ARRAY
Use \fB--array ARRAY\fR to improve speed when
\fBi3fyra\fP is executed from a script that already
have the array, f.i. \fBi3run\fP and \fBi3Kornhe\fP\&.

.SS -a, --float
Autolayout. If current window is tiled: floating
enabled If window is floating, it will be put in a
visible container. If there is no visible
containers. The window will be placed in a hidden
container. If no containers exist, container
\&'A'will be created and the window will be put
there.

.SS -l, --layout         LAYOUT
AB is point on the X axis, calculated from the
left side if INT is positive, from the right side
if it is negative. AC and BD is on Y axis from
the top if INT is positive, from the bottom if it
is negative. The whole argument needs to be
quoted. Example:

.PP
`i3fyra --layout 'AB=-300 BD=420'

.PP
LAYOUT argument can also be the word 'redo', if it
is, the last layout appended will be restored.

.SS -m, --move           DEST
DEST can either be the name of a container
(A|B|C|D), or it's position relative to the
current container with a direction:[\fBl\fR|\fBleft\fR]
[\fBr\fR|\fBright\fR][\fBu\fR|\fBup\fR][\fBd\fR|\fBdown\fR] If the
container doesnt exist it is created. If argument
is a direction and there is no container in that
direction, Connected container(s) visibility is
toggled. If current window is floating or not
inside ABCD, normal movement is performed.
Distance for moving floating windows with this
action can be defined with the \fB--speed\fR option.
Example: \fB$ i3fyra --speed 30 -m r\fR Will move
current window 30 pixels to the right, if it is
floating.

.SS -s, --show           CONTAINER
If it doesn't exist, it will be created and
current window will be put in it. If it is
visible, nothing happens.

.SH ENVIRONMENT
.SS I3FYRA_WS
Workspace to use for i3fyra. If not set, the firs
workspace that request to create the layout will
be used.

.SS I3FYRA_MAIN_CONTAINER
This container will be the chosen when a container
is requested but not given. When using the command
autolayout (\fB-a\fR) for example, if the window is
floating it will be sent to the main container, if
no other containers exist. Defaults to A.

.SS I3FYRA_ORIENTATION
If set to \fBvertical\fR main split will be \fBAC\fR and
families will be \fBAB\fR and \fBCD\fR\&. Otherwise main
split will be \fBAB\fR and families will be \fBAC\fR and
\fBBD\fR\&.

.SS I3_KING_PID_FILE
When i3king is running this file contains the pid
of the i3king process. It is used by \fBi3fyra\fP to
know if i3king is running, if it is, it will try
to match windows against the rules when \fB--float\fR
option toggles the floating state to tiled.

.SH CONTACT
Send bugs and feature requests to:
.br
https://github.com/budlabs/i3ass/issues

.SH COPYRIGHT
Copyright (c) 2017-2025, budRich of budlabs
.br
SPDX-License-Identifier: MIT
