#!/bin/bash

: "${I3FYRA_MAIN_CONTAINER:=A}"
: "${I3FYRA_WS:=}"
: "${I3FYRA_ORIENTATION:=horizontal}"
: "${XDG_RUNTIME_DIR:=/tmp}"
: "${I3_KING_PID_FILE:=$XDG_RUNTIME_DIR/i3ass/i3king.pid}"

main(){

  local arg

  [[ ${_o[clear-virtuals]} ]] && {
    for k in A B C D; do i3var set "i34VP${k}" ; done
    exit
  }

  for _action in assign-to move show hide layout float orientation; do
    [[ ${arg:=${_o[$_action]}} ]] && break
  done

  [[ $arg ]] || ERX "not a valid operation: $0 $*"

  initialize_globals

  [[ ${_o[layout]} ]] && arg=${arg/${ori[main]}/main}
  ((_o[force]))       || arg=$(virtual_position "$arg")

  case "$_action" in

    move )
      if [[ $arg =~ ^[ABCD]$ ]]; then
        active_move_to_container "$arg"
      elif [[ ${arg:0:1} =~ [urld] ]]; then
        active_move_in_direction "${arg:0:1}"
      else
        ERX "'$arg' is not a valid argument for --move"
      fi
    ;;
    show        ) container_show "$arg" ;;
    hide        ) container_hide "$arg" ;;
    layout      ) apply_splits "$arg"   ;;
    float       ) float_toggle          ;;
    orientation ) orientation "$arg"    ;;

  esac

  [[ $_action =~ move|show|float && ${i3list[TWC]} ]] \
    && messy "[con_id=${i3list[TWC]}]" focus
}

__dir=$(dirname $(readlink -f "${BASH_SOURCE[0]}")) #bashbud
source "$__dir/_init.sh"                            #bashbud
