#!/bin/bash

: "${I3FYRA_MAIN_CONTAINER:=A}"
: "${I3FYRA_WS:=}"
: "${I3FYRA_ORIENTATION:=horizontal}"
: "${XDG_RUNTIME_DIR:=/tmp}"
: "${I3_KING_PID_FILE:=$XDG_RUNTIME_DIR/i3ass/i3king.pid}"

main(){

  local arg

  [[ ${_o[clear-virtuals]} ]] && {
    for k in A B C D; do i3var set "i34VP${k}" ; done
    exit
  }

  for _action in move show hide layout float orientation mono; do
    
    [[ ${arg:=${_o[$_action]}} ]] || continue
    err="i3fyra: argument for '--$_action': '$arg' not valid!"

    case "$_action" in
      move ) 
        ex="A|B|C|D|l|r|u|d|left|right|up|down"
        [[ $arg =~ ^(${ex})$ ]] || ERX "$err expected ($ex)"
        ;;
      
      show|hide ) [[ $arg =~ ^[ABCD]+$ ]] || ERX "$err expected (A|B|C|D)" ;;
      layout    ) [[ $arg =~ = || $arg = redo ]] || ERX "$err"             ;;
      float     ) (($#)) && ERX "$err expected 0 arguments got '($*)'"     ;;
      orientation )
        ex="vertical|horizontal"
        [[ $arg =~ ${ex} ]] || ERX "$err expected ($ex)" 
        ;;
    esac

    unset err ex
    break

  done

  [[ $arg ]] || ERX "not a valid operation: $0 $*"

  initialize_globals

  [[ ${_o[layout]} ]] && arg=${arg/${ori[main]}/main}
  ((_o[force]))       || arg=$(virtual_position "$arg")

  case "$_action" in

    move )
      if [[ $arg =~ ^[ABCD]$ ]]
        then active_move_to_container "$arg"
        else active_move_in_direction "${arg:0:1}"
      fi
    ;;
    show        ) container_show "$arg" ;;
    hide        ) container_hide "$arg" ;;
    layout      ) apply_splits "$arg"   ;;
    float       ) float_toggle          ;;
    orientation ) orientation "$arg"    ;;
    mono        ) monocle_toggle        ;;

  esac

  [[ $_action =~ move|show|float && ${i3list[TWC]} ]] \
    && messy "[con_id=${i3list[TWC]}]" focus
}

__dir=$(dirname $(readlink -f "${BASH_SOURCE[0]}")) #bashbud
source "$__dir/_init.sh"                            #bashbud
