#!/bin/bash

NAME="i3mtm"
VERSION="0.2"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-07-19"
UPDATED="2017-11-19"

about="
$NAME - $VERSION - $UPDATED
created: $CREATED by $AUTHOR
*******************************
When launched without options, i3mtm checks
floating status of current window. If it is
tiled, the window becomes floating.
If it is floating, a search for marks is done,
if no marks are found, window becomes tiled.
Otherwise a dmenu asks for a mark to move window to.
If no selection is made, window is tiled but not moved.
Otherwise window is tiled and moved to selected mark.

With -m option window is treaded as if it was floating
even if it is tiled. (menu is forced)  

usage
-----
\`\$ $NAME [OPTION]\`

| option | argument | function                   |
|:-------|:---------|:---------------------------|
| -v     |          | show version info and exit |
| -h     |          | show this help and exit    |

examples
--------
you could replace your floating toggle binding with this:  
\`\`\`
bindsym Mod3+f exec --no-startup-id exec i3mtm  
bindsym Mod3+Shift+f exec --no-startup-id exec i3mtm -m  
\`\`\`

dependencies
------------
* i3get
* dmenu

contact
-------
$CONTACT
"

while getopts :vh option
do
  case "${option}" in
    v) printf '%s\n' \
         "$NAME - version: $VERSION" \
         "updated: $UPDATED by $AUTHOR"
       exit ;;
    h) printf '%s\n' "${about}" && exit ;;
  esac
done

IGNORE_MARKS=
# IGNORE_MARKS="alfa,beta,sidebar"
DMENU_OPTIONS=
# DMENU_OPTIONS="-h 16 -fn Inconsolata-18:bold"


show_menu(){
  mrks=$(comm -3 <(printf '%s' "${IGNORE_MARKS}" | tr ',' "\n" | sort) \
              <(i3-msg -t get_marks | tr -d '[]"' | tr ',' "\n" | sort) \
              | awk '{$2=$2};1' )
  [[ -z $mrks ]] && \
    i3-msg "[con_id=${cur[0]}]" floating disable, focus && exit
  trg=$(printf '%s' "${mrks}" | dmenu ${DMENU_OPTIONS} -p "move to mark:")
  if [[ -z $trg ]];then 
    i3-msg "[con_id=${cur[0]}]" floating disable, focus 
  else
    i3-msg "[con_id=${cur[0]}]" floating disable, move to mark "${trg}"
    i3-msg "[con_id=${cur[0]}]" focus
  fi
}


cur=($(i3get -r nf))
if [[ $1 = '-m' ]] || [[ ${cur[1]#*_} =~ on ]];then 
  show_menu
else
  i3-msg "[con_id=${cur[0]}]" floating enable, focus
fi
