#!/usr/bin/env bash

___printversion(){
  
cat << 'EOB' >&2
i3flip - version: 0.101
updated: 2021-05-28 by budRich
EOB
}



main(){

  [[ -f /tmp/i3flip_lock ]] && exit
  touch /tmp/i3flip_lock
  trap 'rm /tmp/i3flip_lock' EXIT HUP INT

  declare -g _msgstring
  declare -i next prev

  _dir=$1

  # __o[verbose]=1
  ((__o[verbose])) && ERM $'\n'"target direction: $_dir"
  _dir=${_dir,,}

  read -r layout last first pos size < <(
    i3viswiz --parent ${__o[json]:+--json "${__o[json]}"} \
             --debug grouplayout,lastingroup,firstingroup,grouppos,groupsize \
             --debug-format "%v "
    )            
  
  ((__o[verbose])) && ERM "w" "layout:$layout" "last:$last" \
                              "first:$first" "pos:$pos" "size:$size"

  ((size < 2)) && ERX only container in group

  case "${_dir:0:1}" in

    r|d|n ) 
      next=1 prev=0
      [[ $layout =~ tabbed|splith ]] \
        && ldir=right || ldir=down
    ;;

    l|u|p )
      prev=1 next=0
      [[ $layout =~ tabbed|splith ]] \
        && ldir=left || ldir=up
    ;;

    *     ) ERX "$1 is not a valid direction" ;;
  esac

  # focus/move normally
  if (( (pos  > 1 && pos < size)       
   || ( (pos == 1 && next)
   ||   (pos == size && prev) ) )); then
   
   ((__o[move])) && cmd=move || cmd=focus
   messy "$cmd  $ldir"
  
  # warp focus/move to end of group
  elif ((pos == 1)); then
    if ((__o[move])); then
      messy "[con_id=$last] mark --add --toggle fliptmp"
      messy "move to mark fliptmp"
      messy "[con_id=$last] mark --add --toggle fliptmp"
    else
      messy "[con_id=$last] focus"
    fi

  # warp focus/move to start of group, (move+swap)
  else
    if ((__o[move])); then
      messy "[con_id=$first] mark --add --toggle fliptmp"
      messy "move to mark fliptmp, swap container with mark fliptmp"
      messy "[con_id=$first] mark --add --toggle fliptmp"
    else
      messy "[con_id=$first] focus"
    fi
  fi

  ((__o[verbose])) || qflag='-q'
  [[ -n $_msgstring ]] && i3-msg "${qflag:-}" "$_msgstring"
}

___printhelp(){
  
cat << 'EOB' >&2
i3flip - Tabswitching done right


SYNOPSIS
--------
i3flip [--move|-m] [--json JSON] [--verbose] [--dryrun] DIRECTION
i3flip --help|-h
i3flip --version|-v

OPTIONS
-------

--move|-m  
Move the current container instead of changing
focus.


--json JSON  
use JSON instead of output from  i3-msg -t
get_tree


--verbose  
Print more information to stderr.


--dryrun  
Don't execute any i3 commands.

--help|-h  
Show help and exit.


--version|-v  
Show version and exit.

EOB
}


set -E
trap '[ "$?" -ne 98 ] || exit 98' ERR

ERX() { >&2 echo  "[ERROR] $*" ; exit 98 ;}
ERR() { >&2 echo  "[WARNING] $*"  ;}
ERM() { >&2 echo  "$*"  ;}
ERH(){
  ___printhelp >&2
  [[ -n "$*" ]] && printf '\n%s\n' "$*" >&2
  exit 98
}

messy() {
  # arguments are valid i3-msg arguments
  (( __o[verbose] )) && ERM "m $*"
  (( __o[dryrun]  )) || _msgstring+="$*;"
}


declare -A __o
options="$(
  getopt --name "[ERROR]:i3flip" \
    --options "mhv" \
    --longoptions "move,json:,verbose,dryrun,help,version," \
    -- "$@" || exit 98
)"

eval set -- "$options"
unset options

while true; do
  case "$1" in
    --move       | -m ) __o[move]=1 ;; 
    --json       ) __o[json]="${2:-}" ; shift ;;
    --verbose    ) __o[verbose]=1 ;; 
    --dryrun     ) __o[dryrun]=1 ;; 
    --help       | -h ) ___printhelp && exit ;;
    --version    | -v ) ___printversion && exit ;;
    -- ) shift ; break ;;
    *  ) break ;;
  esac
  shift
done

[[ ${__lastarg:="${!#:-}"} =~ ^--$|${0}$ ]] \
  && __lastarg="" 


main "${@}"


