#!/usr/bin/env bash

___printversion(){
  
cat << 'EOB' >&2
i3menu - version: 0.1
updated: 2021-05-28 by budRich
EOB
}


# environment variables
: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${I3MENU_DIR:=$XDG_CONFIG_HOME/i3menu}"


main(){

  
  # __o[verbose]=1

  ((__o[verbose])) && {
    declare -gi _stamp
    _stamp=$(date +%s%N)
    ERM $'\n'"---i3menu start---"
  }

  _menu_command="
    rofi -theme <(themefile)
    ${__o[options]:+${__o[options]}}
    ${__o[filter]:+-filter \"${__o[filter]}\"}
    ${__o[show]:+-show \"${__o[show]}\"}
    ${__o[modi]:+-modi \"${__o[modi]}\"}
    ${__o[prompt]:+-p \"${__o[prompt]} \"}
  "

  _menu_command=${_menu_command//$'\n'/ }

  [[ -n ${__o[modi]}${__o[show]} ]] || {

    _menu_command+="-dmenu "

    # if we have stuff on stdin, put
    # that in a tempfile that way we can do stuff ( wc in setincludes() )
    # without worrying that we close and lose whats in stdin
    [[ ! -t 0 ]] && {
      _tmp_list_file=$(mktemp)
      trap 'rm "$_tmp_list_file"' EXIT INT
      cp /dev/stdin "$_tmp_list_file"
    }
  }

  # default includes
  : "${__o[include]:=pel}"

  declare -A i3list
  eval "$(eval i3list "${__o[target]}")"

  [[ ${__o[layout]} =~ ^[ABCD]$ ]] \
    && __o[layout]=$(getvirtualpos "${__o[layout]}")

  setgeometry "${__o[layout]:-default}"
  setincludes

  if [[ -f $_tmp_list_file && ${__o[top]} ]];then
    awk -f <(topsort) "$_tmp_list_file"
  elif [[ -f $_tmp_list_file ]]; then
    cat "$_tmp_list_file"
  fi | {
    ((__o[verbose])) && verbose_outro
    ((__o[dryrun]))  || eval "$_menu_command"
  }
}


___printhelp(){
  
cat << 'EOB' >&2
i3menu - Adds more features to rofi when used in i3wm


SYNOPSIS
--------
i3menu [--theme THEME] [--layout|-a LAYOUT] [--include|-i INCLUDESTRING] [--top|-t TOP] [--xpos|-x INT] [--xoffset INT] [--ypos|-y INT] [--yoffset INT] [--width|-w INT] [--options|-o OPTIONS] [--prompt|-p PROMPT]  [--filter|-f FILTER] [--show MODE] [--modi MODI] [--target TARGET] [--orientation ORIENTATION] [--anchor INT] [--height INT] [--fallback FALLBACK] [--no-auto-position] 
i3menu --help|-h
i3menu --version|-v
i3menu [--verbose] [--dryrun]

OPTIONS
-------

--theme THEME  
If a .rasi file with same name as THEME exist in
I3MENU_DIR/themes, it's content will get appended
to theme file before showing the menu.  

$ echo "list" | i3menu --theme red  
this will use the the file:
I3MENU_DIR/themes/red.rasi

If no matching themefile is found,
I3MENU_DIR/themes/default.rasi will be used  (and
created if it doesn't exist).


--layout|-a LAYOUT  
This is where i3menu differs the most from normal
rofi behavior and is the only option that truly
depends on i3, i3list (and i3fyra if the value is
A|B|C|D). If this option is not set, the menu will
default to a single line (dmenu like) menu at the
top of the screen. If however a value to this
option is one of the following:  


| LAYOUT     | menu location and dimensions 
|:-----------|:---------------
| mouse      | At the mouse position (requires xdotool)
| window     | The currently active window.
| titlebar   | The titlebar of the currently active window.
| tab        | The tab (or titlebar if it isn't tabbed) of the currently active window.
| A,B,C or D | The i3fyra container of the same name if it is visible. If target container isn't visible the menu will be displayed at the default location.

titlebar and tab LAYOUT will be displayed as a
single line (dmenu like) menu, and the other
LAYOUTS will be of vertical (combobox) layout with
the prompt and entrybox above the list.  

The position of the menu can be further
manipulated by using
--xpos,--ypos,--width,--height,--orientation,--include.  

$ echo "list" | i3menu --prompt "select: "
--layout window --xpos -50 --ypos 30  
The command above would create a menu with the
same size and position as the current window, but
place it 50px to the left of the window, and 30px
below the lower of the window.


--include|-i INCLUDESTRING  
INCLUDESTRING can be set to force which elements
of the menu to include. INCLUDESTRING can be one
or more of the following character:  


| char | element  |
|:-----|:---------|
|p | prompt   |
|e | entrybox |
|l | list     |

echo "list" | i3menu --include le --prompt "enter
a value: "  
The command above will result in a menu without
the prompt element.  

i3menu --include pe --prompt "enter a value: "  
The command above will result in a menu without a
list element. (just an inputbox).  

It's also worth mentioning that i3menu adapts to
the objects it knows before creating the menu.
This means that if no input stream (list) exist,
no list element will be included, the same goes
for the prompt.  


--top|-t TOP  
If TOP is set, the input stream (LIST) will get
matched against TOP. Lines in LIST with an exact
MATCH of those in TOP will get moved to the TOP of
LIST before the menu is created.


$ printf '%s\n' one two three four | i3menu --top
"$(printf '%s\n' two four)"  

will result in a list looking like this:  
two four one three



--xpos|-x INT  
Sets the X position of the menu to INT. If this
option is set, it will override any automatic
position of the X coordinate.


--xoffset INT  
Adds INT to the calculated X position of the menu
before it is displayed. XPOS can be either
positive or negative.

EXAMPLE  
If both --layout is set to window and --xpos is
set to -50, the menu will be placed 50 pixels to
the left of the active window but have the same
dimensions as the window.


--ypos|-y INT  
Sets the Y position of the menu to INT. If this
option is set, it will override any automatic
position of the Y coordinate.


--yoffset INT  
Adds INT to the calculated Y position of the menu
before it is displayed. INT can be either positive
or negative.

EXAMPLE  
If both --layout is set to titlebar and --ypos is
set to 50, the menu will be placed 50 pixels below
the active window.


--width|-w INT  
Changes the width of the menu. If the argument to
--width ends with a % character the width will be
that many percentages of the screenwidth. Without
% absolute width in pixels will be set.


--options|-o OPTIONS  
The argument is a string of aditional options to
pass to rofi.  

$ i3menu --prompt "Enter val: " --options
'-matching regex'  
will result in a call to rofi looking something
like this:  
rofi -p "Enter val: " -matching regex -dmenu

Note that the rofi options: -p, -filter, -show,
-modi could be entered to as arguments to i3menu
--options, but it is recommended to use: --prompt,
--filter, --show and --modi instead, since this
will make i3menu optimize the layout better.


--prompt|-p PROMPT  
Sets the prompt of the menu to PROMPT.


--filter|-f FILTER  
Sets the inputbox text/filter to FILTER. Defaults
to blank string.


--show MODE  
This is a short hand for the rofi option -show.
So instead of doing this:  
$ i3menu -o '-show run' , you can do this:  
$ i3menu --show run


--modi MODI  
This is a short hand for the rofi option -modi.
So instead of doing this:  
$ i3menu -o '-modi run,drun -show run' , you can
do this:  
$ i3menu --modi run,drun --show run


--target TARGET  
TARGET is a string containing additional options
passed to i3list. This can be used to change the
target window when --layout is set to:
window,titlebar or tab.


--orientation ORIENTATION  
This forces the layout of the menu to be either
vertical or horizontal. If --layout is set to
window, the layout will always be vertical.


--anchor INT  
Sets the "anchor" point of the menu. The default
is 1. 1 means the top left corner, 9 means the
bottom right corner. Corner in this context
doesn't refer to the corners of the screen, but
the corners of the menu. If the anchor is top left
(1), the menu will grow from that point.


--height INT  
Overrides the calculated height of the menu.


--fallback FALLBACK  
FALLBACK can be a string of optional options the
will be tried if the first layout fails. A layout
can fail of three reasons:

1. layout is window or container, but no list is passed. If no fallback is set, titlebar layout will get tried.
2. layout is container but container is not visible. If no fallback is set, default layout will get tried.
3. layout is window, tab or titlebar but no target window is found. If no fallback is set, default layout will get tried.


Example  

   $ echo -e "one\ntwo\nthree" | i3menu --layout A --fallback '--layout mouse --width 300'



The example above will display a menu at the
mouse pointer if container A isn't visible.

Fallbacks can be nested, but make sure to
alternate quotes:  


   $ echo -e "one\ntwo\nthree" | i3menu --layout A --fallback '--layout window --fallback "--layout mouse --width 300"'



The example above would first try to display a
menu with --layout A if that fails, it will try a
menu with --layout window and last if no target
window can be found, the menu will get displayed
at the mouse pointer.

#options-verbose-description

Print additional information to STDERR

#options-dryrun-description

Do not execute any i3-msg commands


--no-auto-position  

--help|-h  
Show help and exit.


--version|-v  
Show version and exit

--verbose  

--dryrun  
EOB
}


adjustposition() {
  declare -i newy newx opty

  declare -A geo

  # xdotool --getwindowgeometry --shell ; example:
  # WINDOW=6291526
  # X=0
  # Y=43
  # WIDTH=1568
  # HEIGHT=171
  # SCREEN=0
  #
  # AWK turns the output from: WINDOW=.. -> geo[WINDOW]=...
  # before it's evaluated

  eval "$(xdotool search --sync --classname rofi getwindowgeometry --shell | \
    awk '{printf("geo[%s]=%s\n",$1,$2)}' FS='='
  )"

  opty=$(( ${1:-0} <= -0 ? i3list[WAH]-( (opty*-1)+geo[HEIGHT] ) : $1 ))

  newy=$(( opty < i3list[WAY] ? i3list[WAY] 
         : opty+geo[HEIGHT] > i3list[WAH] ? i3list[WAH]-geo[HEIGHT] 
         : opty ))

  newx=$(( geo[X] < i3list[WAX] ? i3list[WAX] 
         : geo[X]+geo[WIDTH] > i3list[WAW] ? i3list[WAW]-geo[WIDTH] 
         : geo[X] ))

  xdotool windowmove "${geo[WINDOW]}" "$newx" "$newy"
}

createconf() {
local trgdir="$1"
declare -a aconfdirs

aconfdirs=(
"$trgdir/base"
"$trgdir/themes"
)

mkdir -p "${aconfdirs[@]}"

cat << 'EOCONF' > "$trgdir/base/i3menu.rasi"
/**
* i3menu rofi theme - by budRich 2018
* derived from my old Oneliner.rasi
* based on dmenu.rasi by Dave Davenport
*/

#window {
  anchor:     @window-anchor;
  location:   north west;
  padding:    2px;

  width:     @window-width;
  height:    @window-height;
  x-offset:  @window-x;
  y-offset:  @window-y;
  children:  @window-content;
}

#horibox {
  orientation: horizontal;
  children:    @horibox-content;
}

#inputbar {
  children:   @inputbar-content;
}

#listview {
  layout:     @listview-layout;
  lines:      @listview-lines;
  spacing:    5px;
  dynamic:    true;
}

#entry {
  expand:     @entry-expand;
  width:      @entry-width;
}


#element {
  padding: 0px 2px;
}

#element selected {
  text-color: @selfg;
  background-color: @selbg;
}

#prompt {
  text-color: @promptfg;
  background-color: @promptbg;
}

// syntax:ssDslash
EOCONF

cat << 'EOCONF' > "$trgdir/base/themevars.rasi"
* {
  fg:          #988d6d;
  bg:          #FFFFD8;

  activefg:    #FFFFE8;
  activehl:    #424242;
  activebg:    #8888c8;

  inactivefg:  #988d6d;
  inactivebg:  #e8eb98;

  red:         #b85c57;
  green:       #40883f;
  blue:        #0287c8;
  yellow:      #989848;
  cyan:        #4fa8a8;
  magenta:     #8888c8;

  light:       #FFFFE8;
  dark:        #424242;

  fg2:         #B8B09A;
  comment:     #B8B09A;

  bg2:         #FFFFE8;

  selectedfg:  #FFFFE8;
  selectedbg:  #8888c8;

  font1: "monospace 12";
}

EOCONF

cat << 'EOCONF' > "$trgdir/themes/default.rasi"
*{
  background-color:    @bg2;
  border-color:        @bg2;
  text-color:          @fg;
  selbg:               @activebg;
  selfg:               @activefg;
  promptbg:            @bg2;
  promptfg:            @activehl;
  font:                @font1; 
}
EOCONF

cat << 'EOCONF' > "$trgdir/themes/accent.rasi"
*{
  background-color:    @activebg;
  border-color:        @activebg;
  text-color:          @activehl;
  selbg:               @activehl;
  selfg:               @activebg;
  promptbg:            @activehl;
  promptfg:            @activebg;
  font:                @font1; 
}
EOCONF

cat << 'EOCONF' > "$trgdir/themes/red.rasi"
*{
  background-color:    @red;
  border-color:        @red;
  text-color:          @light;
  selbg:               @dark;
  selfg:               @light;
  promptbg:            @light;
  promptfg:            @red;
  font:                @font1; 
}


EOCONF

cat << 'EOCONF' > "$trgdir/themes/dark.rasi"
*{
  background-color:    @dark;
  border-color:        @dark;
  text-color:          @light;
  selbg:               @light;
  selfg:               @dark;
  promptbg:            @light;
  promptfg:            @dark;
  font:                @font1; 
}
EOCONF

cat << 'EOCONF' > "$trgdir/themes/light.rasi"
*{
  background-color:    @light;
  border-color:        @light;
  text-color:          @dark;
  selbg:               @dark;
  selfg:               @light;
  promptbg:            @dark;
  promptfg:            @light;
  font:                @font1; 
}
EOCONF

}

ERM(){ >&2 echo "$*"; }
ERR(){ >&2 echo "[WARNING]" "$*"; }
ERX(){ >&2 echo "[ERROR]" "$*" && exit 1 ; }

getvirtualpos() {

  local target=$1

  # block below sets "virtual" i3fyra position i3list[VPx]
  [[ ${target:=${__o[layout]}} =~ A|B|C|D ]] && {
    declare -i vpos
    q=([0]=A [1]=B [2]=C [3]=D)
    for k in "${!q[@]}"; do
      vpos=${i3list[VP${q[$k]}]:=$k}
      # if target=A , i3list[VPA]=2 -> target=@@2
      (( k != vpos )) && [[ $target =~ ${q[k]} ]] \
        && target=${target//${q[$k]}/@@$vpos}
    done

    [[ $target =~ @@ ]] && for k in "${!q[@]}"; do
      # if k=2, target=@@2, q[2]=C -> target=C
      target=${target//@@$k/${q[$k]}}
    done
  }

  echo "$target"
}

setfallback(){

 __o[fallback]=""

 declare -a opts
 # using eval here to silence shellcheck
 # $* (__o[fallback]) can look like this: 
 # __o[fallback]='--layout D --fallback "--layout A"'
 eval "opts=($*)"

 eval set -- "$(getopt --name "i3menu" \
   --options "a:i:t:x:y:w:o:p:f:" \
   --longoptions "theme:,layout:,include:,top:,xpos:,xoffset:,ypos:,yoffset:,width:,options:,prompt:,filter:,show:,modi:,target:,orientation:,anchor:,height:,fallback:" \
   -- "${opts[@]}"
 )"

 while true; do
   case "$1" in
     --theme      ) __o[theme]="${2:-}" ; shift ;;
     --layout     | -a ) __o[layout]="${2:-}" ; shift ;;
     --include    | -i ) __o[include]="${2:-}" ; shift ;;
     --top        | -t ) __o[top]="${2:-}" ; shift ;;
     --xpos       | -x ) __o[xpos]="${2:-}" ; shift ;;
     --xoffset    ) __o[xoffset]="${2:-}" ; shift ;;
     --ypos       | -y ) __o[ypos]="${2:-}" ; shift ;;
     --yoffset    ) __o[yoffset]="${2:-}" ; shift ;;
     --width      | -w ) __o[width]="${2:-}" ; shift ;;
     --options    | -o ) __o[options]="${2:-}" ; shift ;;
     --prompt     | -p ) __o[prompt]="${2:-}" ; shift ;;
     --filter     | -f ) __o[filter]="${2:-}" ; shift ;;
     --show       ) __o[show]="${2:-}" ; shift ;;
     --modi       ) __o[modi]="${2:-}" ; shift ;;
     --target     ) __o[target]="${2:-}" ; shift ;;
     --orientation ) __o[orientation]="${2:-}" ; shift ;;
     --anchor     ) __o[anchor]="${2:-}" ; shift ;;
     --height     | -h ) __o[height]="${2:-}" ; shift ;;
     --fallback   ) __o[fallback]="${2:-}" ; shift ;;
     -- ) shift ; break ;;
     *  ) break ;;
   esac
   shift
 done

 [[ ${__o[layout]} =~ A|B|C|D ]] \
   && __o[layout]=$(getvirtualpos "${__o[layout]}")
}

defaultoffset(){
  __xpos=0
  __ypos=0
  __o[xoffset]=0
  __o[yoffset]=0
  __o[width]=${i3list[WAW]}
  __height=20
  __o[layout]=default
  __orientation=horizontal
  __anchor=1
}

setgeometry(){

  __layout="$1"

  # default geometry
  : "${__xpos:=${__o[xpos]:-0}}"
  : "${__ypos:=${__o[ypos]:-0}}"
  : "${__o[xoffset]:=0}"
  : "${__o[yoffset]:=0}"
  : "${__o[width]:=${i3list[WAW]}}"
  : "${__height:=${__o[height]:-${i3list[TWB]:-20}}}"
  : "${__o[anchor]:=1}"
  : "${__orientation:=horizontal}"

  # if layout is window or container, but no list -> titlebar
  [[ $__layout =~ A|B|C|D|window && ! -f $_tmp_list_file ]] && {
    defaultoffset
    if [[ -n ${__o[fallback]:-} ]]; then
      __layout=fallback
      setfallback "${__o[fallback]}"
      setgeometry "${__o[layout]:-default}"
      return
    else
      __layout=titlebar
    fi
  }

  # if layout is container but container is not visible -> default
  [[ $__layout =~ A|B|C|D ]] && [[ ! ${i3list[LVI]} =~ [${__layout}] ]] && {
    defaultoffset
    if [[ -n ${__o[fallback]:-} ]]; then
      __layout=fallback
      setfallback "${__o[fallback]}"
      setgeometry "${__o[layout]:-default}"
      return
    else
      __layout=default
    fi
  }

  # if layout is window, tab or titlebar but no target window -> default
  [[ $__layout =~ window|tab|titlebar ]] && [[ -z ${i3list[TWC]} ]] && {
    defaultoffset
    if [[ -n ${__o[fallback]:-} ]]; then
      __layout=fallback
      setfallback "${__o[fallback]}"
      setgeometry "${__o[layout]:-default}"
      return
    else
      __layout=default
    fi
  }

  case "$__layout" in

    titlebar  ) 
      __ypos=$((i3list[TWY]+i3list[WAY]))
      __xpos=$((i3list[TWX]+i3list[WAX]))
      __o[width]=${i3list[TWW]}
      __height=${i3list[TWB]}
      __orientation=horizontal
    ;;

    window    )
        __xpos=$((i3list[TWX]+i3list[WAX]))
        __ypos=$((i3list[TWY]+i3list[WAY]))
        __o[width]=${i3list[TWW]}
        __height=${i3list[TWH]}
        __orientation=vertical
        __o[orientation]=""
    ;;

    bottom )
      __ypos=$((i3list[WAH]-i3list[AWB]))
    ;;

    tab       ) 
      if ((i3list[TTW]==i3list[TWW])); then
        __xpos=$((i3list[TWX]+i3list[WAX]))
        __o[width]=${i3list[TWW]}
      else
        __xpos=$((i3list[TTX]+i3list[TWX]))
        __o[width]=${i3list[TTW]}
      fi
      __ypos=$((i3list[TWY]+i3list[WAY]))
      __height=${i3list[TWB]}
      __orientation=horizontal
    ;;

    A|B|C|D ) 
      case "$__layout" in
        A) 
          __xpos=0
          __ypos=0
          __o[width]=${i3list[SAB]:-${i3list[WAW]}}
          __height=${i3list[SAC]:-${i3list[WAH]}}
        ;;

        B) 
          __xpos=${i3list[SAB]:-0}
          __ypos=0
          __o[width]=$((i3list[WAW]-__xpos))
          __height=${i3list[SBD]:-${i3list[SAC]:-${i3list[WAH]}}}
        ;;

        C) 
          __xpos=0
          __ypos=${i3list[SAC]:-0}
          __o[width]=${i3list[SCD]:-${i3list[SAB]:-${i3list[WAW]}}}
          __height=$((i3list[WAH]-__ypos))
        ;;

        D) 
          __xpos=${i3list[SCD]:-${i3list[SAB]:-0}}
          __ypos=${i3list[SBD]:-0}
          __o[width]=$((i3list[WAW]-__xpos))
          __height=$((i3list[WAH]-__ypos))
        ;;
      esac

      ((__height))   || __height="${i3list[WAH]}"
      ((__o[width])) || __o[width]="${i3list[WAW]}"
      __orientation=vertical
      __o[orientation]=""
    ;;

    mouse )

      # xdotool getmouselocation --shell ; example:
      # X=667
      # Y=175
      # SCREEN=0
      # WINDOW=6291526
      #
      # AWK turns the output from: WINDOW=.. -> xdo_geo[WINDOW]=...
      # before it's evaluated

      declare -A xdo_geo

      eval "$(xdotool getmouselocation --shell | \
        awk '{ printf("xdo_geo[%s]=%s\n",$1,$2) }' FS='='
      )"

      __xpos="$((xdo_geo[X]))"
      __ypos="$((xdo_geo[Y]))"
    ;;

  esac

  case ${__o[anchor]:=1} in
    1   ) __anchor="north west" ;;
    2   ) __anchor="north" ;;
    3   ) __anchor="north east" ;;
    4   ) __anchor="west" ;;
    5   ) __anchor="center" ;;
    6   ) __anchor="east" ;;
    7   ) __anchor="south west" ;;
    8   ) __anchor="south" ;;
    9   ) __anchor="south east" ;;
    *   ) __anchor="north west" ;;
  esac

  [[ -n ${__o[xpos]:-} ]] && {
    if ((__o[xpos]<0)) || ((__o[xpos]==-0)); then
      __xpos=$((i3list[WAW]-((__o[xpos]*-1)+__o[width])))
    else
      __xpos=${__o[xpos]}
    fi
  }

  ((${__height%px}<20)) && __height=20
  [[ -n ${__o[height]} ]] && __height="${__o[height]}"

  [[ -n ${__o[ypos]:-} ]] && __ypos=${__o[ypos]}

  [[ ${__o[xoffset]} =~ ^[0-9-]+$ ]] && __xpos=$((__xpos+__o[xoffset]))
  [[ ${__o[yoffset]} =~ ^[0-9-]+$ ]] && __ypos=$((__ypos+__o[yoffset]))

  [[ ${__o[width]} =~ [%]$ ]] || __o[width]=${__o[width]}px
  __height+="px"
}

setincludes(){
  local entry_expand entry_width listview_layout 
  local window_content horibox_content listview_lines

  [[ -n ${__o[prompt]} ]] || __o[include]=${__o[include]/[p]/}

  if [[ -f $_tmp_list_file ]]; then

    [[ -n ${__o[orientation]:-} ]] && {
      __orientation=${__o[orientation]}
      [[ $__orientation = vertical ]] && [[ -z ${__o[height]} ]] \
        && __height=0
    }
    listview_layout="$__orientation"
    listview_lines=$(wc -l < "$_tmp_list_file")


  else
    __o[include]=${__o[include]/[l]/}
    entry_expand=true
    entry_width=0
  fi

  [[ ${__o[include]} =~ [p] ]] && inc+=(prompt)
  [[ ${__o[include]} =~ [e] ]] && inc+=(entry)

  if [[ $__orientation = vertical ]]; then
   
    __o[include]=${inc[*]}
    window_content="[ mainbox ]"
    inputbar_content="[${__o[include]//' '/','}]"
  else
    # limit number of lines in horizontal menu, 
    # it gets slow otherwise...
    ((listview_lines > 500)) && listview_lines=500
    [[ ${__o[include]} =~ [l] ]] && inc+=(listview)
    __o[include]=${inc[*]}
    horibox_content="[${__o[include]//' '/','}]"
    window_content="[ horibox ]"
  fi


  # TODO: why this test for negative zero???
  if [[ $__layout = mouse ]] || { [[ $__ypos -lt 0 || $__ypos = -0 ]] && ((__o[anchor]<7)) ;}; then

    ERM "$__ypos ${__o[width]}"
    adjustposition "$__ypos" &
    
    # move window offscreen if:
    { 
      # negative ypos or xpos is outside of screen
      { [[ $__ypos -lt 0 || $__ypos = -0 ]] && ((__o[anchor]<7)) ;} || \
      ((__xpos+${__o[width]%px}>i3list[WAW]))

    } && __ypos=9999999

  fi 


  __themelayout="
  * {
    window-anchor:    ${__anchor:-north west};
    window-content:   ${window_content:-[horibox,listview]};
    horibox-content:  ${horibox_content:-[prompt, entry]};
    window-width:     ${__o[width]};
    window-height:    ${__height};
    window-x:         ${__xpos}px;
    window-y:         ${__ypos}px;
    listview-layout:  ${listview_layout:-horizontal};
    listview-lines:   ${listview_lines:-50};
    entry-expand:     ${entry_expand:-false};
    entry-width:      ${entry_width:-10em};
    inputbar-content: ${inputbar_content:-[prompt,entry]};
  }
  "
}

themefile(){
  local themebase themefile themevars usrtheme

  usrtheme=${__o[theme]:-default}
  usrtheme="${usrtheme%.rasi}"

  themefile="${I3MENU_DIR}/themes/$usrtheme.rasi"
  themebase="${I3MENU_DIR}/base/i3menu.rasi"
  themevars="${I3MENU_DIR}/base/themevars.rasi"

  if [[ ! -f $themebase ]] || [[ ! -f $themevars ]]; then
    createconf "${I3MENU_DIR}"
  fi

  [[ -f $themefile ]] || {
    [[ -d ${I3MENU_DIR} ]] || createconf "${I3MENU_DIR}"
    themefile="${I3MENU_DIR}/themes/default.rasi"
  }

  echo "${__themelayout:-}"
  cat "$themevars" "$themefile" "$themebase"
}

topsort() {
# this function generates a awk script

# dynamically created BEGIN block for awk
# with array top_arg[] where each key is a line
# from the ARG passed to --top
echo "BEGIN{"
while read -r top_line ; do
  echo "top_arg[\"$top_line\"]=1"
done <<< "${__o[top]}"
echo "}"

cat << 'END_OF_AWK_MAIN_LOOP'
{
  if ($0 in top_arg) {first[$0]=1}
  else {rest[NR]=$0}
}

END {
  for (k in first) { print k }
  for (i=1;i<=NR;i++) {
    if (i in rest)
      print rest[i]
  }
}
END_OF_AWK_MAIN_LOOP
}

verbose_outro() {
  declare -i delta=$(( ($(date +%s%N)-_stamp) /1000 ))
  declare -i time=$(((delta / 1000) % 1000))

  ERM $'\n'"------ theme start ------"
  themefile >&2
  ERM "------ theme end ------"
  ERM $'\n'"cmd: $_menu_command"
  ERM  $'\n'"---i3menu done: ${time}ms---"$'\n'
}
declare -A __o
options="$(
  getopt --name "[ERROR]:i3menu" \
    --options "a:i:t:x:y:w:o:p:f:hv" \
    --longoptions "theme:,layout:,include:,top:,xpos:,xoffset:,ypos:,yoffset:,width:,options:,prompt:,filter:,show:,modi:,target:,orientation:,anchor:,height:,fallback:,no-auto-position,help,version,verbose,dryrun," \
    -- "$@" || exit 98
)"

eval set -- "$options"
unset options

while true; do
  case "$1" in
    --theme      ) __o[theme]="${2:-}" ; shift ;;
    --layout     | -a ) __o[layout]="${2:-}" ; shift ;;
    --include    | -i ) __o[include]="${2:-}" ; shift ;;
    --top        | -t ) __o[top]="${2:-}" ; shift ;;
    --xpos       | -x ) __o[xpos]="${2:-}" ; shift ;;
    --xoffset    ) __o[xoffset]="${2:-}" ; shift ;;
    --ypos       | -y ) __o[ypos]="${2:-}" ; shift ;;
    --yoffset    ) __o[yoffset]="${2:-}" ; shift ;;
    --width      | -w ) __o[width]="${2:-}" ; shift ;;
    --options    | -o ) __o[options]="${2:-}" ; shift ;;
    --prompt     | -p ) __o[prompt]="${2:-}" ; shift ;;
    --filter     | -f ) __o[filter]="${2:-}" ; shift ;;
    --show       ) __o[show]="${2:-}" ; shift ;;
    --modi       ) __o[modi]="${2:-}" ; shift ;;
    --target     ) __o[target]="${2:-}" ; shift ;;
    --orientation ) __o[orientation]="${2:-}" ; shift ;;
    --anchor     ) __o[anchor]="${2:-}" ; shift ;;
    --height     ) __o[height]="${2:-}" ; shift ;;
    --fallback   ) __o[fallback]="${2:-}" ; shift ;;
    --no-auto-position ) __o[no-auto-position]=1 ;; 
    --help       | -h ) ___printhelp && exit ;;
    --version    | -v ) ___printversion && exit ;;
    --verbose    ) __o[verbose]=1 ;; 
    --dryrun     ) __o[dryrun]=1 ;; 
    -- ) shift ; break ;;
    *  ) break ;;
  esac
  shift
done

[[ ${__lastarg:="${!#:-}"} =~ ^--$|${0}$ ]] \
  && __lastarg="" 


main "${@:-}"


