'\" t
.nh
.TH I3GET   2024-04-21 budlabs "User Manuals"
.SH NAME
i3get \- prints info about a specific window to stdout

.SH SYNOPSIS
\fBi3get [OPTIONS]\fR

.SH OPTIONS
.EX
-c, --class        CLASS         | target windows with CLASS  
-n, --conid        CON_ID        | target windows with CON_ID  
-h, --help                       | print help and exit  
-d, --id           WIN_ID        | target windows with WIN_ID  
-i, --instance     INSTANCE      | target windows with INSTANCE
--json             TREE          | Use TREE instead of the output of `i3-msg -t get_tree`
-m, --mark         MARK          | MARK | target containers with MARK  
-r, --print        OUTPUT        | what to print. defaults to 'n'  
--print-format     FORMAT_STRING | %v is value, %k is name. default: '%vn'  
--role             ROLE          | match ROLE against window_role  
-y, --synk                       | block script till window exist.
--timeout          SECONDS       | seconds for --synk to timeout (defaults to 60)  
-t, --title        TITLE         | target windows with TITLE  
-o, --titleformat  TITLE_FORMAT  | match TITLE_FORMAT against title_format  
--type             TYPE          | match TYPE against window_type  
--verbose                        | print messages to stderr  
-v, --version                    | print version info and exit  
--winid            WIN_ID        | target windows with WIN_ID  
.EE

.SS -r, --print        OUTPUT
\fIOUTPUT\fP can be one or more of the following
characters:

.TS
allbox;
l l l 
l l l .
\fBcharacter\fP	\fBprint\fP	\fBreturn\fP
\fBt\fR	title	string
\fBc\fR	class	string
\fBi\fR	instance	string
\fBd\fR	Window ID	INT
\fBn\fR	Con_Id (default)	INT
\fBm\fR	mark	JSON list
\fBw\fR	workspace number	INT
\fBW\fR	workspace name	STRING
\fBa\fR	is active	true or false
\fBf\fR	floating state	string
\fBo\fR	title format	string
\fBe\fR	fullscreen	1 or 0
\fBs\fR	sticky	true or false
\fBu\fR	urgent	true or false
\fBy\fR	window_type	string
\fBr\fR	window_role	string
.TE

.PP
Each character in OUTPUT will be tested and the
return value will be printed on a new line. If no
value is found, \fB--i3get could not find:
CHARACTER\fR will get printed.

.PP
In the example below, the target window did not have a mark:

.EX
$ i3get -r tfcmw
/dev/pts/9
user_off
URxvt
--i3get could not find: m
1
.EE

.SH USAGE
Search for \fBCRITERIA\fR in the output of \fBi3-msg -t get_tree\fR,
return desired information.
If no arguments are passed,
\fBcon_id\fR of active window is returned.
If there is more then one criterion,
all of them must be true to get results.


.SH EXAMPLES
search for window with instance name sublime_text.
Request workspace, title and floating state.

.EX
$ i3get --instance sublime_text --print wtf 
1
~/src/bash/i3ass/i3get (i3ass) - Sublime Text
user_off
.EE

.SH CONTACT
Send bugs and feature requests to:
.br
https://github.com/budlabs/i3ass/issues

.SH COPYRIGHT
Copyright (c) 2017-2025, budRich of budlabs
.br
SPDX-License-Identifier: MIT
